package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * AccionReporteAbuso generated by hbm2java
 */
@Entity
@Table(name = "accion_reporte_abuso")
public class AccionReporteAbuso implements java.io.Serializable {

	private int idAccionReporteAbuso;
	private String nombreAccionReporteAbuso;
	private String descripcionAccionReporteAbuso;
	private Set<ReporteAbuso> reporteAbusos = new HashSet<ReporteAbuso>(0);

	public AccionReporteAbuso() {
	}

	public AccionReporteAbuso(int idAccionReporteAbuso,
			String nombreAccionReporteAbuso,
			String descripcionAccionReporteAbuso) {
		this.idAccionReporteAbuso = idAccionReporteAbuso;
		this.nombreAccionReporteAbuso = nombreAccionReporteAbuso;
		this.descripcionAccionReporteAbuso = descripcionAccionReporteAbuso;
	}
	public AccionReporteAbuso(int idAccionReporteAbuso,
			String nombreAccionReporteAbuso,
			String descripcionAccionReporteAbuso,
			Set<ReporteAbuso> reporteAbusos) {
		this.idAccionReporteAbuso = idAccionReporteAbuso;
		this.nombreAccionReporteAbuso = nombreAccionReporteAbuso;
		this.descripcionAccionReporteAbuso = descripcionAccionReporteAbuso;
		this.reporteAbusos = reporteAbusos;
	}

	@Id
	@Column(name = "id_accion_reporte_abuso", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdAccionReporteAbuso() {
		return this.idAccionReporteAbuso;
	}

	public void setIdAccionReporteAbuso(int idAccionReporteAbuso) {
		this.idAccionReporteAbuso = idAccionReporteAbuso;
	}

	@Column(name = "nombre_accion_reporte_abuso", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreAccionReporteAbuso() {
		return this.nombreAccionReporteAbuso;
	}

	public void setNombreAccionReporteAbuso(String nombreAccionReporteAbuso) {
		this.nombreAccionReporteAbuso = nombreAccionReporteAbuso;
	}

	@Column(name = "descripcion_accion_reporte_abuso", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionAccionReporteAbuso() {
		return this.descripcionAccionReporteAbuso;
	}

	public void setDescripcionAccionReporteAbuso(
			String descripcionAccionReporteAbuso) {
		this.descripcionAccionReporteAbuso = descripcionAccionReporteAbuso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accionReporteAbuso")
	public Set<ReporteAbuso> getReporteAbusos() {
		return this.reporteAbusos;
	}

	public void setReporteAbusos(Set<ReporteAbuso> reporteAbusos) {
		this.reporteAbusos = reporteAbusos;
	}

}
