package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Bitacora generated by hbm2java
 */
@Entity
@Table(name = "bitacora")
public class Bitacora implements java.io.Serializable {

    private int idBitacora;
    private TipoBitacora tipoBitacora;
    private Idea idea;
    private Usuario usuario;
    private EstatusBitacora estatusBitacora;
    private String tituloBitacora;
    private String descripcionBitacora;
    private Date fechaBitacora;
    private Set<Aviso> avisos = new HashSet<Aviso>(0);
    private Set<Envio> envios = new HashSet<Envio>(0);

    public Bitacora() {
    }

    public Bitacora(TipoBitacora tipoBitacora, Idea idea, Usuario usuario
            , EstatusBitacora estatusBitacora, String tituloBitacora
            , String descripcionBitacora, java.sql.Date fechaBitacora) {
        this.tipoBitacora = tipoBitacora;
        this.idea = idea;
        this.usuario = usuario;
        this.estatusBitacora = estatusBitacora;
        this.tituloBitacora = tituloBitacora;
        this.descripcionBitacora = descripcionBitacora;
        this.fechaBitacora = fechaBitacora;
    }

    public Bitacora(int idBitacora, TipoBitacora tipoBitacora, Idea idea,
            Usuario usuario, EstatusBitacora estatusBitacora,
            String tituloBitacora, String descripcionBitacora,
            Date fechaBitacora) {
        this.idBitacora = idBitacora;
        this.tipoBitacora = tipoBitacora;
        this.idea = idea;
        this.usuario = usuario;
        this.estatusBitacora = estatusBitacora;
        this.tituloBitacora = tituloBitacora;
        this.descripcionBitacora = descripcionBitacora;
        this.fechaBitacora = fechaBitacora;
    }

    public Bitacora(int idBitacora, TipoBitacora tipoBitacora, Idea idea,
            Usuario usuario, EstatusBitacora estatusBitacora,
            String tituloBitacora, String descripcionBitacora,
            Date fechaBitacora, Set<Envio> envios) {
        this.idBitacora = idBitacora;
        this.tipoBitacora = tipoBitacora;
        this.idea = idea;
        this.usuario = usuario;
        this.estatusBitacora = estatusBitacora;
        this.tituloBitacora = tituloBitacora;
        this.descripcionBitacora = descripcionBitacora;
        this.fechaBitacora = fechaBitacora;
        this.envios = envios;
    }

    public Bitacora(int idBitacora, TipoBitacora tipoBitacora, Idea idea,
            Usuario usuario, EstatusBitacora estatusBitacora,
            String tituloBitacora, String descripcionBitacora,
            Date fechaBitacora, Set<Aviso> avisos, Set<Envio> envios) {
        this.idBitacora = idBitacora;
        this.tipoBitacora = tipoBitacora;
        this.idea = idea;
        this.usuario = usuario;
        this.estatusBitacora = estatusBitacora;
        this.tituloBitacora = tituloBitacora;
        this.descripcionBitacora = descripcionBitacora;
        this.fechaBitacora = fechaBitacora;
        this.avisos = avisos;
        this.envios = envios;
    }


    @Id
    @Column(name = "id_bitacora", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdBitacora() {
        return this.idBitacora;
    }

    public void setIdBitacora(int idBitacora) {
        this.idBitacora = idBitacora;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_bitacora_id", nullable = false)
    @NotNull
    public TipoBitacora getTipoBitacora() {
        return this.tipoBitacora;
    }

    public void setTipoBitacora(TipoBitacora tipoBitacora) {
        this.tipoBitacora = tipoBitacora;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false)
    @NotNull
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus_bitacora_id", nullable = false)
    @NotNull
    public EstatusBitacora getEstatusBitacora() {
        return this.estatusBitacora;
    }

    public void setEstatusBitacora(EstatusBitacora estatusBitacora) {
        this.estatusBitacora = estatusBitacora;
    }

    @Column(name = "titulo_bitacora", nullable = false, length = 100)
    @NotNull
    @Length(max = 100)
    public String getTituloBitacora() {
        return this.tituloBitacora;
    }

    public void setTituloBitacora(String tituloBitacora) {
        this.tituloBitacora = tituloBitacora;
    }

    @Column(name = "descripcion_bitacora", nullable = false, length = 400)
    @NotNull
    @Length(max = 400)
    public String getDescripcionBitacora() {
        return this.descripcionBitacora;
    }

    public void setDescripcionBitacora(String descripcionBitacora) {
        this.descripcionBitacora = descripcionBitacora;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_bitacora", nullable = false, length = 13)
    @NotNull
    public Date getFechaBitacora() {
        return this.fechaBitacora;
    }

    public void setFechaBitacora(Date fechaBitacora) {
        this.fechaBitacora = fechaBitacora;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacora")
    public Set<Aviso> getAvisos() {
        return this.avisos;
    }

    public void setAvisos(Set<Aviso> avisos) {
        this.avisos = avisos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "bitacora")
    public Set<Envio> getEnvios() {
        return this.envios;
    }

    public void setEnvios(Set<Envio> envios) {
        this.envios = envios;
    }
}
