package mx.uam.azc.link.model;
// Generated 9/05/2011 08:34:11 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ClasificacionIdea generated by hbm2java
 */
@Entity
@Table(name = "clasificacion_idea")
public class ClasificacionIdea implements java.io.Serializable {

    private ClasificacionIdeaId id;
    private Idea idea;
    private TipoIdea tipoIdea;

    public ClasificacionIdea() {
    }

    public ClasificacionIdea(ClasificacionIdeaId id, Idea idea,
            TipoIdea tipoIdea) {
        this.id = id;
        this.idea = idea;
        this.tipoIdea = tipoIdea;
    }

    public ClasificacionIdea(Idea idea,
            TipoIdea tipoIdea) {
        this.id = new ClasificacionIdeaId(
                            tipoIdea.getIdTipoIdea()
                            , idea.getIdIdea());
        this.idea = idea;
        this.tipoIdea = tipoIdea;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "tipoIdeaId", column =
        @Column(name = "tipo_idea_id", nullable = false)),
        @AttributeOverride(name = "ideaId", column =
        @Column(name = "idea_id", nullable = false))})
    @NotNull
    public ClasificacionIdeaId getId() {
        return this.id;
    }

    public void setId(ClasificacionIdeaId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_idea_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public TipoIdea getTipoIdea() {
        return this.tipoIdea;
    }

    public void setTipoIdea(TipoIdea tipoIdea) {
        this.tipoIdea = tipoIdea;
    }
}
