package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClasificacionIdeaId generated by hbm2java
 */
@Embeddable
public class ClasificacionIdeaId implements java.io.Serializable {

    private int tipoIdeaId;
    private int ideaId;

    public ClasificacionIdeaId() {
    }

    public ClasificacionIdeaId(int tipoIdeaId, int ideaId) {
        this.tipoIdeaId = tipoIdeaId;
        this.ideaId = ideaId;
    }

    @Column(name = "tipo_idea_id", nullable = false)
    public int getTipoIdeaId() {
        return this.tipoIdeaId;
    }

    public void setTipoIdeaId(int tipoIdeaId) {
        this.tipoIdeaId = tipoIdeaId;
    }

    @Column(name = "idea_id", nullable = false)
    public int getIdeaId() {
        return this.ideaId;
    }

    public void setIdeaId(int ideaId) {
        this.ideaId = ideaId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ClasificacionIdeaId)) {
            return false;
        }
        ClasificacionIdeaId castOther = (ClasificacionIdeaId) other;

        return (this.getTipoIdeaId() == castOther.getTipoIdeaId())
                && (this.getIdeaId() == castOther.getIdeaId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getTipoIdeaId();
        result = 37 * result + this.getIdeaId();
        return result;
    }
}
