package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ComoLograrlo generated by hbm2java
 */
@Entity
@Table(name = "como_lograrlo")
public class ComoLograrlo implements java.io.Serializable {

    private int idComoLograrlo;
    private Idea idea;
    private String descripcionComoLograrlo;
    private Date fechaComoLograrlo;

    public ComoLograrlo() {
    }

    public ComoLograrlo(int idComoLograrlo, Idea idea,
            String descripcionComoLograrlo) {
        this.idComoLograrlo = idComoLograrlo;
        this.idea = idea;
        this.descripcionComoLograrlo = descripcionComoLograrlo;
    }

    public ComoLograrlo(int idComoLograrlo, Idea idea,
            String descripcionComoLograrlo, Date fechaComoLograrlo) {
        this.idComoLograrlo = idComoLograrlo;
        this.idea = idea;
        this.descripcionComoLograrlo = descripcionComoLograrlo;
        this.fechaComoLograrlo = fechaComoLograrlo;
    }

    @Id
    @Column(name = "id_como_lograrlo", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdComoLograrlo() {
        return this.idComoLograrlo;
    }

    public void setIdComoLograrlo(int idComoLograrlo) {
        this.idComoLograrlo = idComoLograrlo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "descripcion_como_lograrlo", nullable = false, length = 5000)
    @NotNull
    @Length(max = 5000)
    public String getDescripcionComoLograrlo() {
        return this.descripcionComoLograrlo;
    }

    public void setDescripcionComoLograrlo(String descripcionComoLograrlo) {
        this.descripcionComoLograrlo = descripcionComoLograrlo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_como_lograrlo", length = 13)
    public Date getFechaComoLograrlo() {
        return this.fechaComoLograrlo;
    }

    public void setFechaComoLograrlo(Date fechaComoLograrlo) {
        this.fechaComoLograrlo = fechaComoLograrlo;
    }
}
