package mx.uam.azc.link.model;
// Generated 28/04/2011 04:36:39 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Comunidad generated by hbm2java
 */
@Entity
@Table(name = "comunidad")
public class Comunidad implements java.io.Serializable {

    private int idComunidad;
    private EstatusComunidad estatusComunidad;
    private String nombreComunidad;
    private String descripcionComunidad;
    private String tituloComunidad;
    private Set<Envio> envios = new HashSet<Envio>(0);
    private Set<MiembroComunidad> miembroComunidads =
                                    new HashSet<MiembroComunidad>(0);

    public Comunidad() {
    }

    public Comunidad(int idComunidad, EstatusComunidad estatusComunidad,
            String nombreComunidad, String descripcionComunidad,
            String tituloComunidad) {
        this.idComunidad = idComunidad;
        this.estatusComunidad = estatusComunidad;
        this.nombreComunidad = nombreComunidad;
        this.descripcionComunidad = descripcionComunidad;
        this.tituloComunidad = tituloComunidad;
    }

    public Comunidad(int idComunidad, EstatusComunidad estatusComunidad,
            String nombreComunidad, String descripcionComunidad,
            String tituloComunidad, Set<Envio> envios,
            Set<MiembroComunidad> miembroComunidads) {
        this.idComunidad = idComunidad;
        this.estatusComunidad = estatusComunidad;
        this.nombreComunidad = nombreComunidad;
        this.descripcionComunidad = descripcionComunidad;
        this.tituloComunidad = tituloComunidad;
        this.envios = envios;
        this.miembroComunidads = miembroComunidads;
    }

    @Id
    @Column(name = "id_comunidad", unique = true, nullable = false)
    public int getIdComunidad() {
        return this.idComunidad;
    }

    public void setIdComunidad(int idComunidad) {
        this.idComunidad = idComunidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus_comunidad_id", nullable = false)
    @NotNull
    public EstatusComunidad getEstatusComunidad() {
        return this.estatusComunidad;
    }

    public void setEstatusComunidad(EstatusComunidad estatusComunidad) {
        this.estatusComunidad = estatusComunidad;
    }

    @Column(name = "nombre_comunidad", nullable = false, length = 100)
    @NotNull
    @Length(max = 100)
    public String getNombreComunidad() {
        return this.nombreComunidad;
    }

    public void setNombreComunidad(String nombreComunidad) {
        this.nombreComunidad = nombreComunidad;
    }

    @Column(name = "descripcion_comunidad", nullable = false)
    @NotNull
    public String getDescripcionComunidad() {
        return this.descripcionComunidad;
    }

    public void setDescripcionComunidad(String descripcionComunidad) {
        this.descripcionComunidad = descripcionComunidad;
    }

    @Column(name = "titulo_comunidad", nullable = false, length = 100)
    @NotNull
    @Length(max = 100)
    public String getTituloComunidad() {
        return this.tituloComunidad;
    }

    public void setTituloComunidad(String tituloComunidad) {
        this.tituloComunidad = tituloComunidad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "comunidad")
    public Set<Envio> getEnvios() {
        return this.envios;
    }

    public void setEnvios(Set<Envio> envios) {
        this.envios = envios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "comunidad")
    public Set<MiembroComunidad> getMiembroComunidads() {
        return this.miembroComunidads;
    }

    public void setMiembroComunidads(Set<MiembroComunidad> miembroComunidads) {
        this.miembroComunidads = miembroComunidads;
    }
}
