package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConfiguracionUsuario generated by hbm2java
 */
@Entity
@Table(name = "configuracion_usuario")
public class ConfiguracionUsuario implements java.io.Serializable {

	private int idConfiguracionUsuario;
	private boolean envioDeCorreos;
	private boolean avisoPreguntas;
	private boolean avisoBitacoras;
	private boolean avisoParticipaciones;
	private boolean avisoIdeas;
	private boolean avisoSeguidores;
	private boolean avisoNuevoLugar;
	private boolean almacenarPosicionGeografica;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public ConfiguracionUsuario() {
	}

        public ConfiguracionUsuario(
			boolean envioDeCorreos, boolean avisoPreguntas,
			boolean avisoBitacoras, boolean avisoParticipaciones,
			boolean avisoIdeas, boolean avisoSeguidores,
			boolean avisoNuevoLugar, boolean almacenarPosicionGeografica) {
		this.envioDeCorreos = envioDeCorreos;
		this.avisoPreguntas = avisoPreguntas;
		this.avisoBitacoras = avisoBitacoras;
		this.avisoParticipaciones = avisoParticipaciones;
		this.avisoIdeas = avisoIdeas;
		this.avisoSeguidores = avisoSeguidores;
		this.avisoNuevoLugar = avisoNuevoLugar;
		this.almacenarPosicionGeografica = almacenarPosicionGeografica;
	}
	public ConfiguracionUsuario(int idConfiguracionUsuario,
			boolean envioDeCorreos, boolean avisoPreguntas,
			boolean avisoBitacoras, boolean avisoParticipaciones,
			boolean avisoIdeas, boolean avisoSeguidores,
			boolean avisoNuevoLugar, boolean almacenarPosicionGeografica) {
		this.idConfiguracionUsuario = idConfiguracionUsuario;
		this.envioDeCorreos = envioDeCorreos;
		this.avisoPreguntas = avisoPreguntas;
		this.avisoBitacoras = avisoBitacoras;
		this.avisoParticipaciones = avisoParticipaciones;
		this.avisoIdeas = avisoIdeas;
		this.avisoSeguidores = avisoSeguidores;
		this.avisoNuevoLugar = avisoNuevoLugar;
		this.almacenarPosicionGeografica = almacenarPosicionGeografica;
	}
	public ConfiguracionUsuario(int idConfiguracionUsuario,
			boolean envioDeCorreos, boolean avisoPreguntas,
			boolean avisoBitacoras, boolean avisoParticipaciones,
			boolean avisoIdeas, boolean avisoSeguidores,
			boolean avisoNuevoLugar, boolean almacenarPosicionGeografica,
			Set<Usuario> usuarios) {
		this.idConfiguracionUsuario = idConfiguracionUsuario;
		this.envioDeCorreos = envioDeCorreos;
		this.avisoPreguntas = avisoPreguntas;
		this.avisoBitacoras = avisoBitacoras;
		this.avisoParticipaciones = avisoParticipaciones;
		this.avisoIdeas = avisoIdeas;
		this.avisoSeguidores = avisoSeguidores;
		this.avisoNuevoLugar = avisoNuevoLugar;
		this.almacenarPosicionGeografica = almacenarPosicionGeografica;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id_configuracion_usuario", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdConfiguracionUsuario() {
		return this.idConfiguracionUsuario;
	}

	public void setIdConfiguracionUsuario(int idConfiguracionUsuario) {
		this.idConfiguracionUsuario = idConfiguracionUsuario;
	}

	@Column(name = "envio_de_correos", nullable = false)
	public boolean isEnvioDeCorreos() {
		return this.envioDeCorreos;
	}

	public void setEnvioDeCorreos(boolean envioDeCorreos) {
		this.envioDeCorreos = envioDeCorreos;
	}

	@Column(name = "aviso_preguntas", nullable = false)
	public boolean isAvisoPreguntas() {
		return this.avisoPreguntas;
	}

	public void setAvisoPreguntas(boolean avisoPreguntas) {
		this.avisoPreguntas = avisoPreguntas;
	}

	@Column(name = "aviso_bitacoras", nullable = false)
	public boolean isAvisoBitacoras() {
		return this.avisoBitacoras;
	}

	public void setAvisoBitacoras(boolean avisoBitacoras) {
		this.avisoBitacoras = avisoBitacoras;
	}

	@Column(name = "aviso_participaciones", nullable = false)
	public boolean isAvisoParticipaciones() {
		return this.avisoParticipaciones;
	}

	public void setAvisoParticipaciones(boolean avisoParticipaciones) {
		this.avisoParticipaciones = avisoParticipaciones;
	}

	@Column(name = "aviso_ideas", nullable = false)
	public boolean isAvisoIdeas() {
		return this.avisoIdeas;
	}

	public void setAvisoIdeas(boolean avisoIdeas) {
		this.avisoIdeas = avisoIdeas;
	}

	@Column(name = "aviso_seguidores", nullable = false)
	public boolean isAvisoSeguidores() {
		return this.avisoSeguidores;
	}

	public void setAvisoSeguidores(boolean avisoSeguidores) {
		this.avisoSeguidores = avisoSeguidores;
	}

	@Column(name = "aviso_nuevo_lugar", nullable = false)
	public boolean isAvisoNuevoLugar() {
		return this.avisoNuevoLugar;
	}

	public void setAvisoNuevoLugar(boolean avisoNuevoLugar) {
		this.avisoNuevoLugar = avisoNuevoLugar;
	}

	@Column(name = "almacenar_posicion_geografica", nullable = false)
	public boolean isAlmacenarPosicionGeografica() {
		return this.almacenarPosicionGeografica;
	}

	public void setAlmacenarPosicionGeografica(
			boolean almacenarPosicionGeografica) {
		this.almacenarPosicionGeografica = almacenarPosicionGeografica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configuracionUsuario")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
