package mx.uam.azc.link.model;
// Generated 11/06/2011 09:16:22 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ContactoUsuario generated by hbm2java
 */
@Entity
@Table(name = "contacto_usuario", uniqueConstraints =
@UniqueConstraint(columnNames = {
    "texto_contacto_usuario", "tipo_contacto_usuario_id"}))
public class ContactoUsuario implements java.io.Serializable {

    private int idContactoUsuario;
    private TipoContactoUsuario tipoContactoUsuario;
    private Usuario usuario;
    private String textoContactoUsuario;
    private String textoComplementario1;
    private String textoComplementario2;
    private String textoComplementario3;

    public ContactoUsuario() {
    }

    public ContactoUsuario(int idContactoUsuario, Usuario usuario,
            String textoContactoUsuario) {
        this.idContactoUsuario = idContactoUsuario;
        this.usuario = usuario;
        this.textoContactoUsuario = textoContactoUsuario;
    }

    public ContactoUsuario(int idContactoUsuario,
            TipoContactoUsuario tipoContactoUsuario, Usuario usuario,
            String textoContactoUsuario) {
        this.idContactoUsuario = idContactoUsuario;
        this.tipoContactoUsuario = tipoContactoUsuario;
        this.usuario = usuario;
        this.textoContactoUsuario = textoContactoUsuario;
    }

    public ContactoUsuario(int idContactoUsuario,
            TipoContactoUsuario tipoContactoUsuario, Usuario usuario,
            String textoContactoUsuario, String textoComplementario1,
            String textoComplementario2, String textoComplementario3) {
        this.idContactoUsuario = idContactoUsuario;
        this.tipoContactoUsuario = tipoContactoUsuario;
        this.usuario = usuario;
        this.textoContactoUsuario = textoContactoUsuario;
        this.textoComplementario1 = textoComplementario1;
        this.textoComplementario2 = textoComplementario2;
        this.textoComplementario3 = textoComplementario3;
    }

    @Id
    @Column(name = "id_contacto_usuario", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdContactoUsuario() {
        return this.idContactoUsuario;
    }

    public void setIdContactoUsuario(int idContactoUsuario) {
        this.idContactoUsuario = idContactoUsuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_contacto_usuario_id", nullable = false)
    @NotNull
    public TipoContactoUsuario getTipoContactoUsuario() {
        return this.tipoContactoUsuario;
    }

    public void setTipoContactoUsuario(
            TipoContactoUsuario tipoContactoUsuario) {
        this.tipoContactoUsuario = tipoContactoUsuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false)
    @NotNull
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Column(name = "texto_contacto_usuario", nullable = false, length = 100)
    @NotNull
    @Length(max = 100)
    public String getTextoContactoUsuario() {
        return this.textoContactoUsuario;
    }

    public void setTextoContactoUsuario(String textoContactoUsuario) {
        this.textoContactoUsuario = textoContactoUsuario;
    }

    @Column(name = "texto_complementario1", length = 100)
    @Length(max = 100)
    public String getTextoComplementario1() {
        return this.textoComplementario1;
    }

    public void setTextoComplementario1(String textoComplementario1) {
        this.textoComplementario1 = textoComplementario1;
    }

    @Column(name = "texto_complementario2", length = 100)
    @Length(max = 100)
    public String getTextoComplementario2() {
        return this.textoComplementario2;
    }

    public void setTextoComplementario2(String textoComplementario2) {
        this.textoComplementario2 = textoComplementario2;
    }

    @Column(name = "texto_complementario3")
    public String getTextoComplementario3() {
        return this.textoComplementario3;
    }

    public void setTextoComplementario3(String textoComplementario3) {
        this.textoComplementario3 = textoComplementario3;
    }
}
