package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Envio generated by hbm2java
 */
@Entity
@Table(name = "envio")
public class Envio implements java.io.Serializable {

	private int idEnvio;
	private Bitacora bitacora;
	private Pregunta pregunta;
	private TicketRegistro ticketRegistro;
	private ReporteAbuso reporteAbuso;
	private Invitacion invitacion;
	private Comunidad comunidad;
	private Aviso aviso;
	private TipoEnvio tipoEnvio;
	private Idea idea;
	private EstatusEnvio estatusEnvio;
	private Usuario usuario;
	private Canica canica;
	private Date fechaRegistroEnvio;
	private Date fechaEnvioEnvio;
	private int numeroIntentosEnvio;
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public Envio() {
	}

public Envio(TipoEnvio tipoEnvio, EstatusEnvio estatusEnvio,
            Comunidad comunidad, Date fechaRegistroEnvio,
            int numeroIntentosEnvio, Idea idea) {
        this.tipoEnvio = tipoEnvio;
        this.estatusEnvio = estatusEnvio;
        this.comunidad = comunidad;
        this.fechaRegistroEnvio = fechaRegistroEnvio;
        this.numeroIntentosEnvio = numeroIntentosEnvio;
        this.idea = idea;
    }

    public Envio(int idEnvio, Bitacora bitacora, Pregunta pregunta,
            Comunidad comunidad, TipoEnvio tipoEnvio, Idea idea,
            EstatusEnvio estatusEnvio, Date fechaRegistroEnvio,
            Date fechaEnvioEnvio, int numeroIntentosEnvio) {
        this.idEnvio = idEnvio;
        this.bitacora = bitacora;
        this.pregunta = pregunta;
        this.comunidad = comunidad;
        this.tipoEnvio = tipoEnvio;
        this.idea = idea;
        this.estatusEnvio = estatusEnvio;
        this.fechaRegistroEnvio = fechaRegistroEnvio;
        this.fechaEnvioEnvio = fechaEnvioEnvio;
        this.numeroIntentosEnvio = numeroIntentosEnvio;
    }

	public Envio(int idEnvio, TipoEnvio tipoEnvio, EstatusEnvio estatusEnvio,
			Date fechaRegistroEnvio, int numeroIntentosEnvio) {
		this.idEnvio = idEnvio;
		this.tipoEnvio = tipoEnvio;
		this.estatusEnvio = estatusEnvio;
		this.fechaRegistroEnvio = fechaRegistroEnvio;
		this.numeroIntentosEnvio = numeroIntentosEnvio;
	}

public Envio(int idEnvio, Bitacora bitacora, Pregunta pregunta,
            TicketRegistro ticketRegistro, ReporteAbuso reporteAbuso,
            Comunidad comunidad, TipoEnvio tipoEnvio, Idea idea,
            EstatusEnvio estatusEnvio, Usuario usuario, Canica canica,
            Date fechaRegistroEnvio, Date fechaEnvioEnvio,
            int numeroIntentosEnvio) {
        this.idEnvio = idEnvio;
        this.bitacora = bitacora;
        this.pregunta = pregunta;
        this.ticketRegistro = ticketRegistro;
        this.reporteAbuso = reporteAbuso;
        this.comunidad = comunidad;
        this.tipoEnvio = tipoEnvio;
        this.idea = idea;
        this.estatusEnvio = estatusEnvio;
        this.usuario = usuario;
        this.canica = canica;
        this.fechaRegistroEnvio = fechaRegistroEnvio;
        this.fechaEnvioEnvio = fechaEnvioEnvio;
        this.numeroIntentosEnvio = numeroIntentosEnvio;
    }

        public Envio(java.sql.Date fechaHoy, TipoEnvio tipoEnvio
            , EstatusEnvio estatusEnvio, int numIntentos
            , Canica canica) {
        this.fechaRegistroEnvio = fechaHoy;
        this.tipoEnvio = tipoEnvio;
        this.estatusEnvio = estatusEnvio;
        this.numeroIntentosEnvio = numIntentos;
        this.canica = canica;
    }

    public Envio(int idEnvio, Bitacora bitacora, Pregunta pregunta,
                    TicketRegistro ticketRegistro, ReporteAbuso reporteAbuso,
                    Comunidad comunidad, Aviso aviso, TipoEnvio tipoEnvio, Idea idea,
                    EstatusEnvio estatusEnvio, Usuario usuario, Canica canica,
                    Date fechaRegistroEnvio, Date fechaEnvioEnvio,
                    int numeroIntentosEnvio, Set<Aviso> avisos) {
            this.idEnvio = idEnvio;
            this.bitacora = bitacora;
            this.pregunta = pregunta;
            this.ticketRegistro = ticketRegistro;
            this.reporteAbuso = reporteAbuso;
            this.comunidad = comunidad;
            this.aviso = aviso;
            this.tipoEnvio = tipoEnvio;
            this.idea = idea;
            this.estatusEnvio = estatusEnvio;
            this.usuario = usuario;
            this.canica = canica;
            this.fechaRegistroEnvio = fechaRegistroEnvio;
            this.fechaEnvioEnvio = fechaEnvioEnvio;
            this.numeroIntentosEnvio = numeroIntentosEnvio;
            this.avisos = avisos;
    }
	public Envio(int idEnvio, Bitacora bitacora, Pregunta pregunta,
			TicketRegistro ticketRegistro, ReporteAbuso reporteAbuso,
			Invitacion invitacion, Comunidad comunidad, Aviso aviso,
			TipoEnvio tipoEnvio, Idea idea, EstatusEnvio estatusEnvio,
			Usuario usuario, Canica canica, Date fechaRegistroEnvio,
			Date fechaEnvioEnvio, int numeroIntentosEnvio, Set<Aviso> avisos) {
		this.idEnvio = idEnvio;
		this.bitacora = bitacora;
		this.pregunta = pregunta;
		this.ticketRegistro = ticketRegistro;
		this.reporteAbuso = reporteAbuso;
		this.invitacion = invitacion;
		this.comunidad = comunidad;
		this.aviso = aviso;
		this.tipoEnvio = tipoEnvio;
		this.idea = idea;
		this.estatusEnvio = estatusEnvio;
		this.usuario = usuario;
		this.canica = canica;
		this.fechaRegistroEnvio = fechaRegistroEnvio;
		this.fechaEnvioEnvio = fechaEnvioEnvio;
		this.numeroIntentosEnvio = numeroIntentosEnvio;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "id_envio", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	public int getIdEnvio() {
		return this.idEnvio;
	}

	public void setIdEnvio(int idEnvio) {
		this.idEnvio = idEnvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bitacora_id")
	public Bitacora getBitacora() {
		return this.bitacora;
	}

	public void setBitacora(Bitacora bitacora) {
		this.bitacora = bitacora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pregunta_id")
	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ticket_registro_id")
	public TicketRegistro getTicketRegistro() {
		return this.ticketRegistro;
	}

	public void setTicketRegistro(TicketRegistro ticketRegistro) {
		this.ticketRegistro = ticketRegistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "reporte_abuso_id")
	public ReporteAbuso getReporteAbuso() {
		return this.reporteAbuso;
	}

	public void setReporteAbuso(ReporteAbuso reporteAbuso) {
		this.reporteAbuso = reporteAbuso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invitacion_id")
	public Invitacion getInvitacion() {
		return this.invitacion;
	}

	public void setInvitacion(Invitacion invitacion) {
		this.invitacion = invitacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "comunidad_id")
	public Comunidad getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(Comunidad comunidad) {
		this.comunidad = comunidad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aviso_id")
	public Aviso getAviso() {
		return this.aviso;
	}

	public void setAviso(Aviso aviso) {
		this.aviso = aviso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_envio_id", nullable = false)
	@NotNull
	public TipoEnvio getTipoEnvio() {
		return this.tipoEnvio;
	}

	public void setTipoEnvio(TipoEnvio tipoEnvio) {
		this.tipoEnvio = tipoEnvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id")
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_envio_id", nullable = false)
	@NotNull
	public EstatusEnvio getEstatusEnvio() {
		return this.estatusEnvio;
	}

	public void setEstatusEnvio(EstatusEnvio estatusEnvio) {
		this.estatusEnvio = estatusEnvio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "canica_id")
	public Canica getCanica() {
		return this.canica;
	}

	public void setCanica(Canica canica) {
		this.canica = canica;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro_envio", nullable = false, length = 13)
	@NotNull
	public Date getFechaRegistroEnvio() {
		return this.fechaRegistroEnvio;
	}

	public void setFechaRegistroEnvio(Date fechaRegistroEnvio) {
		this.fechaRegistroEnvio = fechaRegistroEnvio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_envio_envio", length = 13)
	public Date getFechaEnvioEnvio() {
		return this.fechaEnvioEnvio;
	}

	public void setFechaEnvioEnvio(Date fechaEnvioEnvio) {
		this.fechaEnvioEnvio = fechaEnvioEnvio;
	}

	@Column(name = "numero_intentos_envio", nullable = false)
	public int getNumeroIntentosEnvio() {
		return this.numeroIntentosEnvio;
	}

	public void setNumeroIntentosEnvio(int numeroIntentosEnvio) {
		this.numeroIntentosEnvio = numeroIntentosEnvio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "envio")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

}
