package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusUsuario generated by hbm2java
 */
@Entity
@Table(name = "estatus_usuario")
public class EstatusUsuario implements java.io.Serializable {

    private int idEstatusUsuario;
    private String nombreEstatusUsuario;
    private String definicionEstatusUsuario;
    private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public EstatusUsuario() {
    }

    public EstatusUsuario(int idEstatusUsuario, String nombreEstatusUsuario,
            String definicionEstatusUsuario) {
        this.idEstatusUsuario = idEstatusUsuario;
        this.nombreEstatusUsuario = nombreEstatusUsuario;
        this.definicionEstatusUsuario = definicionEstatusUsuario;
    }

    public EstatusUsuario(int idEstatusUsuario, String nombreEstatusUsuario,
            String definicionEstatusUsuario, Set<Usuario> usuarios) {
        this.idEstatusUsuario = idEstatusUsuario;
        this.nombreEstatusUsuario = nombreEstatusUsuario;
        this.definicionEstatusUsuario = definicionEstatusUsuario;
        this.usuarios = usuarios;
    }

    @Id
    @Column(name = "id_estatus_usuario", unique = true, nullable = false)
    public int getIdEstatusUsuario() {
        return this.idEstatusUsuario;
    }

    public void setIdEstatusUsuario(int idEstatusUsuario) {
        this.idEstatusUsuario = idEstatusUsuario;
    }

    @Column(name = "nombre_estatus_usuario", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusUsuario() {
        return this.nombreEstatusUsuario;
    }

    public void setNombreEstatusUsuario(String nombreEstatusUsuario) {
        this.nombreEstatusUsuario = nombreEstatusUsuario;
    }

    @Column(name = "definicion_estatus_usuario", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusUsuario() {
        return this.definicionEstatusUsuario;
    }

    public void setDefinicionEstatusUsuario(String definicionEstatusUsuario) {
        this.definicionEstatusUsuario = definicionEstatusUsuario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusUsuario")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
}
