package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusNecesidad generated by hbm2java
 */
@Entity
@Table(name = "estatus_necesidad")
public class EstatusNecesidad implements java.io.Serializable {

    private int idEstatusNecesidad;
    private String nombreEstatusNecesidad;
    private String definicionEstatusNecesidad;
    private Set<Necesidad> necesidads = new HashSet<Necesidad>(0);

    public EstatusNecesidad() {
    }

    public EstatusNecesidad(int idEstatusNecesidad,
            String nombreEstatusNecesidad, String definicionEstatusNecesidad) {
        this.idEstatusNecesidad = idEstatusNecesidad;
        this.nombreEstatusNecesidad = nombreEstatusNecesidad;
        this.definicionEstatusNecesidad = definicionEstatusNecesidad;
    }

    public EstatusNecesidad(int idEstatusNecesidad,
            String nombreEstatusNecesidad, String definicionEstatusNecesidad,
            Set<Necesidad> necesidads) {
        this.idEstatusNecesidad = idEstatusNecesidad;
        this.nombreEstatusNecesidad = nombreEstatusNecesidad;
        this.definicionEstatusNecesidad = definicionEstatusNecesidad;
        this.necesidads = necesidads;
    }

    @Id
    @Column(name = "id_estatus_necesidad", unique = true, nullable = false)
    public int getIdEstatusNecesidad() {
        return this.idEstatusNecesidad;
    }

    public void setIdEstatusNecesidad(int idEstatusNecesidad) {
        this.idEstatusNecesidad = idEstatusNecesidad;
    }

    @Column(name = "nombre_estatus_necesidad", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusNecesidad() {
        return this.nombreEstatusNecesidad;
    }

    public void setNombreEstatusNecesidad(String nombreEstatusNecesidad) {
        this.nombreEstatusNecesidad = nombreEstatusNecesidad;
    }

    @Column(name = "definicion_estatus_necesidad", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusNecesidad() {
        return this.definicionEstatusNecesidad;
    }

    public void setDefinicionEstatusNecesidad(String definicionEstatusNecesidad) {
        this.definicionEstatusNecesidad = definicionEstatusNecesidad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusNecesidad")
    public Set<Necesidad> getNecesidads() {
        return this.necesidads;
    }

    public void setNecesidads(Set<Necesidad> necesidads) {
        this.necesidads = necesidads;
    }
}
