package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusComunidad generated by hbm2java
 */
@Entity
@Table(name = "estatus_comunidad")
public class EstatusComunidad implements java.io.Serializable {

    private int idEstatusComunidad;
    private String nombreEstatusComunidad;
    private String definicionEstatusComunidad;
    private Set<Comunidad> comunidads = new HashSet<Comunidad>(0);

    public EstatusComunidad() {
    }

    public EstatusComunidad(int idEstatusComunidad,
            String nombreEstatusComunidad, String definicionEstatusComunidad) {
        this.idEstatusComunidad = idEstatusComunidad;
        this.nombreEstatusComunidad = nombreEstatusComunidad;
        this.definicionEstatusComunidad = definicionEstatusComunidad;
    }

    public EstatusComunidad(int idEstatusComunidad,
            String nombreEstatusComunidad, String definicionEstatusComunidad,
            Set<Comunidad> comunidads) {
        this.idEstatusComunidad = idEstatusComunidad;
        this.nombreEstatusComunidad = nombreEstatusComunidad;
        this.definicionEstatusComunidad = definicionEstatusComunidad;
        this.comunidads = comunidads;
    }

    @Id
    @Column(name = "id_estatus_comunidad", unique = true, nullable = false)
    public int getIdEstatusComunidad() {
        return this.idEstatusComunidad;
    }

    public void setIdEstatusComunidad(int idEstatusComunidad) {
        this.idEstatusComunidad = idEstatusComunidad;
    }

    @Column(name = "nombre_estatus_comunidad", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusComunidad() {
        return this.nombreEstatusComunidad;
    }

    public void setNombreEstatusComunidad(String nombreEstatusComunidad) {
        this.nombreEstatusComunidad = nombreEstatusComunidad;
    }

    @Column(name = "definicion_estatus_comunidad", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusComunidad() {
        return this.definicionEstatusComunidad;
    }

    public void setDefinicionEstatusComunidad
                                           (String definicionEstatusComunidad) {
        this.definicionEstatusComunidad = definicionEstatusComunidad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusComunidad")
    public Set<Comunidad> getComunidads() {
        return this.comunidads;
    }

    public void setComunidads(Set<Comunidad> comunidads) {
        this.comunidads = comunidads;
    }
}
