package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusCritica generated by hbm2java
 */
@Entity
@Table(name = "estatus_critica")
public class EstatusCritica implements java.io.Serializable {

    private int idEstatusCritica;
    private String nombreEstatusCritica;
    private String definicionEstatusCritica;
    private Set<Critica> criticas = new HashSet<Critica>(0);

    public EstatusCritica() {
    }

    public EstatusCritica(int idEstatusCritica, String nombreEstatusCritica,
            String definicionEstatusCritica) {
        this.idEstatusCritica = idEstatusCritica;
        this.nombreEstatusCritica = nombreEstatusCritica;
        this.definicionEstatusCritica = definicionEstatusCritica;
    }

    public EstatusCritica(int idEstatusCritica, String nombreEstatusCritica,
            String definicionEstatusCritica, Set<Critica> criticas) {
        this.idEstatusCritica = idEstatusCritica;
        this.nombreEstatusCritica = nombreEstatusCritica;
        this.definicionEstatusCritica = definicionEstatusCritica;
        this.criticas = criticas;
    }

    @Id
    @Column(name = "id_estatus_critica", unique = true, nullable = false)
    public int getIdEstatusCritica() {
        return this.idEstatusCritica;
    }

    public void setIdEstatusCritica(int idEstatusCritica) {
        this.idEstatusCritica = idEstatusCritica;
    }

    @Column(name = "nombre_estatus_critica", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusCritica() {
        return this.nombreEstatusCritica;
    }

    public void setNombreEstatusCritica(String nombreEstatusCritica) {
        this.nombreEstatusCritica = nombreEstatusCritica;
    }

    @Column(name = "definicion_estatus_critica", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusCritica() {
        return this.definicionEstatusCritica;
    }

    public void setDefinicionEstatusCritica(String definicionEstatusCritica) {
        this.definicionEstatusCritica = definicionEstatusCritica;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusCritica")
    public Set<Critica> getCriticas() {
        return this.criticas;
    }

    public void setCriticas(Set<Critica> criticas) {
        this.criticas = criticas;
    }
    
}
