package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusTicketRegistro generated by hbm2java
 */
@Entity
@Table(name = "estatus_ticket_registro")
public class EstatusTicketRegistro implements java.io.Serializable {

	private int idEstatusTicketRegistro;
	private String nombreEstatusTicketRegistro;
	private String definicionEstatusTicketRegistro;
	private Set<TicketRegistro> ticketRegistros = new HashSet<TicketRegistro>(0);

	public EstatusTicketRegistro() {
	}

	public EstatusTicketRegistro(int idEstatusTicketRegistro,
			String nombreEstatusTicketRegistro,
			String definicionEstatusTicketRegistro) {
		this.idEstatusTicketRegistro = idEstatusTicketRegistro;
		this.nombreEstatusTicketRegistro = nombreEstatusTicketRegistro;
		this.definicionEstatusTicketRegistro = definicionEstatusTicketRegistro;
	}
	public EstatusTicketRegistro(int idEstatusTicketRegistro,
			String nombreEstatusTicketRegistro,
			String definicionEstatusTicketRegistro,
			Set<TicketRegistro> ticketRegistros) {
		this.idEstatusTicketRegistro = idEstatusTicketRegistro;
		this.nombreEstatusTicketRegistro = nombreEstatusTicketRegistro;
		this.definicionEstatusTicketRegistro = definicionEstatusTicketRegistro;
		this.ticketRegistros = ticketRegistros;
	}

	@Id
	@Column(name = "id_estatus_ticket_registro", unique = true, nullable = false)
	public int getIdEstatusTicketRegistro() {
		return this.idEstatusTicketRegistro;
	}

	public void setIdEstatusTicketRegistro(int idEstatusTicketRegistro) {
		this.idEstatusTicketRegistro = idEstatusTicketRegistro;
	}

	@Column(name = "nombre_estatus_ticket_registro", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreEstatusTicketRegistro() {
		return this.nombreEstatusTicketRegistro;
	}

	public void setNombreEstatusTicketRegistro(
			String nombreEstatusTicketRegistro) {
		this.nombreEstatusTicketRegistro = nombreEstatusTicketRegistro;
	}

	@Column(name = "definicion_estatus_ticket_registro", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDefinicionEstatusTicketRegistro() {
		return this.definicionEstatusTicketRegistro;
	}

	public void setDefinicionEstatusTicketRegistro(
			String definicionEstatusTicketRegistro) {
		this.definicionEstatusTicketRegistro = definicionEstatusTicketRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusTicketRegistro")
	public Set<TicketRegistro> getTicketRegistros() {
		return this.ticketRegistros;
	}

	public void setTicketRegistros(Set<TicketRegistro> ticketRegistros) {
		this.ticketRegistros = ticketRegistros;
	}

}
