package mx.uam.azc.link.model;
// Generated 13/07/2011 12:55:13 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusFrase generated by hbm2java
 */
@Entity
@Table(name = "estatus_frase")
public class EstatusFrase implements java.io.Serializable {

	private int idEstatusFrase;
	private String nombreEstatusFrase;
	private String descripcionEstatusFrase;
	private Set<Frase> frases = new HashSet<Frase>(0);

	public EstatusFrase() {
	}

	public EstatusFrase(int idEstatusFrase, String nombreEstatusFrase,
			String descripcionEstatusFrase) {
		this.idEstatusFrase = idEstatusFrase;
		this.nombreEstatusFrase = nombreEstatusFrase;
		this.descripcionEstatusFrase = descripcionEstatusFrase;
	}
	public EstatusFrase(int idEstatusFrase, String nombreEstatusFrase,
			String descripcionEstatusFrase, Set<Frase> frases) {
		this.idEstatusFrase = idEstatusFrase;
		this.nombreEstatusFrase = nombreEstatusFrase;
		this.descripcionEstatusFrase = descripcionEstatusFrase;
		this.frases = frases;
	}

	@Id
	@Column(name = "id_estatus_frase", unique = true, nullable = false)
	public int getIdEstatusFrase() {
		return this.idEstatusFrase;
	}

	public void setIdEstatusFrase(int idEstatusFrase) {
		this.idEstatusFrase = idEstatusFrase;
	}

	@Column(name = "nombre_estatus_frase", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreEstatusFrase() {
		return this.nombreEstatusFrase;
	}

	public void setNombreEstatusFrase(String nombreEstatusFrase) {
		this.nombreEstatusFrase = nombreEstatusFrase;
	}

	@Column(name = "descripcion_estatus_frase", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionEstatusFrase() {
		return this.descripcionEstatusFrase;
	}

	public void setDescripcionEstatusFrase(String descripcionEstatusFrase) {
		this.descripcionEstatusFrase = descripcionEstatusFrase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusFrase")
	public Set<Frase> getFrases() {
		return this.frases;
	}

	public void setFrases(Set<Frase> frases) {
		this.frases = frases;
	}

}
