package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusAviso generated by hbm2java
 */
@Entity
@Table(name = "estatus_aviso")
public class EstatusAviso implements java.io.Serializable {

	private int idEstatusAviso;
	private String nombreEstatusAviso;
	private String definicionEstatusAviso;
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public EstatusAviso() {
	}

	public EstatusAviso(int idEstatusAviso, String nombreEstatusAviso,
			String definicionEstatusAviso) {
		this.idEstatusAviso = idEstatusAviso;
		this.nombreEstatusAviso = nombreEstatusAviso;
		this.definicionEstatusAviso = definicionEstatusAviso;
	}
	public EstatusAviso(int idEstatusAviso, String nombreEstatusAviso,
			String definicionEstatusAviso, Set<Aviso> avisos) {
		this.idEstatusAviso = idEstatusAviso;
		this.nombreEstatusAviso = nombreEstatusAviso;
		this.definicionEstatusAviso = definicionEstatusAviso;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "id_estatus_aviso", unique = true, nullable = false)
	public int getIdEstatusAviso() {
		return this.idEstatusAviso;
	}

	public void setIdEstatusAviso(int idEstatusAviso) {
		this.idEstatusAviso = idEstatusAviso;
	}

	@Column(name = "nombre_estatus_aviso", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreEstatusAviso() {
		return this.nombreEstatusAviso;
	}

	public void setNombreEstatusAviso(String nombreEstatusAviso) {
		this.nombreEstatusAviso = nombreEstatusAviso;
	}

	@Column(name = "definicion_estatus_aviso", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDefinicionEstatusAviso() {
		return this.definicionEstatusAviso;
	}

	public void setDefinicionEstatusAviso(String definicionEstatusAviso) {
		this.definicionEstatusAviso = definicionEstatusAviso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusAviso")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

}
