package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusIntegrante generated by hbm2java
 */
@Entity
@Table(name = "estatus_integrante")
public class EstatusIntegrante implements java.io.Serializable {

    private int idEstatusIntegrante;
    private String nombreEstatusIntegrante;
    private String definicionEstatusIntegrante;
    private Set<Integrante> integrantes = new HashSet<Integrante>(0);

    public EstatusIntegrante() {
    }

    public EstatusIntegrante(int idEstatusIntegrante,
            String nombreEstatusIntegrante, String definicionEstatusIntegrante) {
        this.idEstatusIntegrante = idEstatusIntegrante;
        this.nombreEstatusIntegrante = nombreEstatusIntegrante;
        this.definicionEstatusIntegrante = definicionEstatusIntegrante;
    }

    public EstatusIntegrante(int idEstatusIntegrante,
            String nombreEstatusIntegrante, String definicionEstatusIntegrante,
            Set<Integrante> integrantes) {
        this.idEstatusIntegrante = idEstatusIntegrante;
        this.nombreEstatusIntegrante = nombreEstatusIntegrante;
        this.definicionEstatusIntegrante = definicionEstatusIntegrante;
        this.integrantes = integrantes;
    }

    @Id
    @Column(name = "id_estatus_integrante", unique = true, nullable = false)
    public int getIdEstatusIntegrante() {
        return this.idEstatusIntegrante;
    }

    public void setIdEstatusIntegrante(int idEstatusIntegrante) {
        this.idEstatusIntegrante = idEstatusIntegrante;
    }

    @Column(name = "nombre_estatus_integrante", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusIntegrante() {
        return this.nombreEstatusIntegrante;
    }

    public void setNombreEstatusIntegrante(String nombreEstatusIntegrante) {
        this.nombreEstatusIntegrante = nombreEstatusIntegrante;
    }

    @Column(name = "definicion_estatus_integrante", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusIntegrante() {
        return this.definicionEstatusIntegrante;
    }

    public void setDefinicionEstatusIntegrante(
            String definicionEstatusIntegrante) {
        this.definicionEstatusIntegrante = definicionEstatusIntegrante;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusIntegrante")
    public Set<Integrante> getIntegrantes() {
        return this.integrantes;
    }

    public void setIntegrantes(Set<Integrante> integrantes) {
        this.integrantes = integrantes;
    }
}
