package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusIdea generated by hbm2java
 */
@Entity
@Table(name = "estatus_idea")
public class EstatusIdea implements java.io.Serializable {

    private int idEstatusIdea;
    private String nombreEstatusIdea;
    private String definicionEstatusIdea;
    private Set<Idea> ideas = new HashSet<Idea>(0);

    public EstatusIdea() {
    }

    public EstatusIdea(int idEstatusIdea, String nombreEstatusIdea,
            String definicionEstatusIdea) {
        this.idEstatusIdea = idEstatusIdea;
        this.nombreEstatusIdea = nombreEstatusIdea;
        this.definicionEstatusIdea = definicionEstatusIdea;
    }

    public EstatusIdea(int idEstatusIdea, String nombreEstatusIdea,
            String definicionEstatusIdea, Set<Idea> ideas) {
        this.idEstatusIdea = idEstatusIdea;
        this.nombreEstatusIdea = nombreEstatusIdea;
        this.definicionEstatusIdea = definicionEstatusIdea;
        this.ideas = ideas;
    }

    @Id
    @Column(name = "id_estatus_idea", unique = true, nullable = false)
    public int getIdEstatusIdea() {
        return this.idEstatusIdea;
    }

    public void setIdEstatusIdea(int idEstatusIdea) {
        this.idEstatusIdea = idEstatusIdea;
    }

    @Column(name = "nombre_estatus_idea", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusIdea() {
        return this.nombreEstatusIdea;
    }

    public void setNombreEstatusIdea(String nombreEstatusIdea) {
        this.nombreEstatusIdea = nombreEstatusIdea;
    }

    @Column(name = "definicion_estatus_idea", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusIdea() {
        return this.definicionEstatusIdea;
    }

    public void setDefinicionEstatusIdea(String definicionEstatusIdea) {
        this.definicionEstatusIdea = definicionEstatusIdea;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusIdea")
    public Set<Idea> getIdeas() {
        return this.ideas;
    }

    public void setIdeas(Set<Idea> ideas) {
        this.ideas = ideas;
    }
    
}
