package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusAyudaMonetaria generated by hbm2java
 */
@Entity
@Table(name = "estatus_ayuda_monetaria")
public class EstatusAyudaMonetaria implements java.io.Serializable {

    private int idEstatusAyudaMonetaria;
    private String nombreEstatusAyudaMonetaria;
    private String definicionEstatusAyudaMonetaria;
    private Set<Idea> ideas = new HashSet<Idea>(0);

    public EstatusAyudaMonetaria() {
    }

    public EstatusAyudaMonetaria(int idEstatusAyudaMonetaria,
            String nombreEstatusAyudaMonetaria,
            String definicionEstatusAyudaMonetaria) {
        this.idEstatusAyudaMonetaria = idEstatusAyudaMonetaria;
        this.nombreEstatusAyudaMonetaria = nombreEstatusAyudaMonetaria;
        this.definicionEstatusAyudaMonetaria = definicionEstatusAyudaMonetaria;
    }

    public EstatusAyudaMonetaria(int idEstatusAyudaMonetaria,
            String nombreEstatusAyudaMonetaria,
            String definicionEstatusAyudaMonetaria, Set<Idea> ideas) {
        this.idEstatusAyudaMonetaria = idEstatusAyudaMonetaria;
        this.nombreEstatusAyudaMonetaria = nombreEstatusAyudaMonetaria;
        this.definicionEstatusAyudaMonetaria = definicionEstatusAyudaMonetaria;
        this.ideas = ideas;
    }

    @Id
    @Column(name = "id_estatus_ayuda_monetaria", unique = true, nullable = false)
    public int getIdEstatusAyudaMonetaria() {
        return this.idEstatusAyudaMonetaria;
    }

    public void setIdEstatusAyudaMonetaria(int idEstatusAyudaMonetaria) {
        this.idEstatusAyudaMonetaria = idEstatusAyudaMonetaria;
    }

    @Column(name = "nombre_estatus_ayuda_monetaria", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusAyudaMonetaria() {
        return this.nombreEstatusAyudaMonetaria;
    }

    public void setNombreEstatusAyudaMonetaria(
            String nombreEstatusAyudaMonetaria) {
        this.nombreEstatusAyudaMonetaria = nombreEstatusAyudaMonetaria;
    }

    @Column(name = "definicion_estatus_ayuda_monetaria", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusAyudaMonetaria() {
        return this.definicionEstatusAyudaMonetaria;
    }

    public void setDefinicionEstatusAyudaMonetaria(
            String definicionEstatusAyudaMonetaria) {
        this.definicionEstatusAyudaMonetaria = definicionEstatusAyudaMonetaria;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusAyudaMonetaria")
    public Set<Idea> getIdeas() {
        return this.ideas;
    }

    public void setIdeas(Set<Idea> ideas) {
        this.ideas = ideas;
    }
}
