package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusEnvio generated by hbm2java
 */
@Entity
@Table(name = "estatus_envio")
public class EstatusEnvio implements java.io.Serializable {

    private int idEstatusEnvio;
    private String nombreEstatusEnvio;
    private String definicionEstatusEnvio;
    private Set<Envio> envios = new HashSet<Envio>(0);

    public EstatusEnvio() {
    }

    public EstatusEnvio(int idEstatusEnvio, String nombreEstatusEnvio,
            String definicionEstatusEnvio) {
        this.idEstatusEnvio = idEstatusEnvio;
        this.nombreEstatusEnvio = nombreEstatusEnvio;
        this.definicionEstatusEnvio = definicionEstatusEnvio;
    }

    public EstatusEnvio(int idEstatusEnvio, String nombreEstatusEnvio,
            String definicionEstatusEnvio, Set<Envio> envios) {
        this.idEstatusEnvio = idEstatusEnvio;
        this.nombreEstatusEnvio = nombreEstatusEnvio;
        this.definicionEstatusEnvio = definicionEstatusEnvio;
        this.envios = envios;
    }

    @Id
    @Column(name = "id_estatus_envio", unique = true, nullable = false)
    public int getIdEstatusEnvio() {
        return this.idEstatusEnvio;
    }

    public void setIdEstatusEnvio(int idEstatusEnvio) {
        this.idEstatusEnvio = idEstatusEnvio;
    }

    @Column(name = "nombre_estatus_envio", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusEnvio() {
        return this.nombreEstatusEnvio;
    }

    public void setNombreEstatusEnvio(String nombreEstatusEnvio) {
        this.nombreEstatusEnvio = nombreEstatusEnvio;
    }

    @Column(name = "definicion_estatus_envio", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusEnvio() {
        return this.definicionEstatusEnvio;
    }

    public void setDefinicionEstatusEnvio(String definicionEstatusEnvio) {
        this.definicionEstatusEnvio = definicionEstatusEnvio;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusEnvio")
    public Set<Envio> getEnvios() {
        return this.envios;
    }

    public void setEnvios(Set<Envio> envios) {
        this.envios = envios;
    }
}
