package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusBitacora generated by hbm2java
 */
@Entity
@Table(name = "estatus_bitacora")
public class EstatusBitacora implements java.io.Serializable {

    private int idEstatusBitacora;
    private String nombreEstatusBitacora;
    private String definicionEstatusBitacora;
    private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

    public EstatusBitacora() {
    }

    public EstatusBitacora(int idEstatusBitacora, String nombreEstatusBitacora,
            String definicionEstatusBitacora) {
        this.idEstatusBitacora = idEstatusBitacora;
        this.nombreEstatusBitacora = nombreEstatusBitacora;
        this.definicionEstatusBitacora = definicionEstatusBitacora;
    }

    public EstatusBitacora(int idEstatusBitacora, String nombreEstatusBitacora,
            String definicionEstatusBitacora, Set<Bitacora> bitacoras) {
        this.idEstatusBitacora = idEstatusBitacora;
        this.nombreEstatusBitacora = nombreEstatusBitacora;
        this.definicionEstatusBitacora = definicionEstatusBitacora;
        this.bitacoras = bitacoras;
    }

    @Id
    @Column(name = "id_estatus_bitacora", unique = true, nullable = false)
    public int getIdEstatusBitacora() {
        return this.idEstatusBitacora;
    }

    public void setIdEstatusBitacora(int idEstatusBitacora) {
        this.idEstatusBitacora = idEstatusBitacora;
    }

    @Column(name = "nombre_estatus_bitacora", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusBitacora() {
        return this.nombreEstatusBitacora;
    }

    public void setNombreEstatusBitacora(String nombreEstatusBitacora) {
        this.nombreEstatusBitacora = nombreEstatusBitacora;
    }

    @Column(name = "definicion_estatus_bitacora", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusBitacora() {
        return this.definicionEstatusBitacora;
    }

    public void setDefinicionEstatusBitacora(String definicionEstatusBitacora) {
        this.definicionEstatusBitacora = definicionEstatusBitacora;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusBitacora")
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }

    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }
}
