package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * EstatusSeguidor generated by hbm2java
 */
@Entity
@Table(name = "estatus_seguidor")
public class EstatusSeguidor implements java.io.Serializable {

    private int idEstatusSeguidor;
    private String nombreEstatusSeguidor;
    private String definicionEstatusSeguidor;
    private Set<Seguidor> seguidors = new HashSet<Seguidor>(0);

    public EstatusSeguidor() {
    }

    public EstatusSeguidor(int idEstatusSeguidor, String nombreEstatusSeguidor,
            String definicionEstatusSeguidor) {
        this.idEstatusSeguidor = idEstatusSeguidor;
        this.nombreEstatusSeguidor = nombreEstatusSeguidor;
        this.definicionEstatusSeguidor = definicionEstatusSeguidor;
    }

    public EstatusSeguidor(int idEstatusSeguidor, String nombreEstatusSeguidor,
            String definicionEstatusSeguidor, Set<Seguidor> seguidors) {
        this.idEstatusSeguidor = idEstatusSeguidor;
        this.nombreEstatusSeguidor = nombreEstatusSeguidor;
        this.definicionEstatusSeguidor = definicionEstatusSeguidor;
        this.seguidors = seguidors;
    }

    @Id
    @Column(name = "id_estatus_seguidor", unique = true, nullable = false)
    public int getIdEstatusSeguidor() {
        return this.idEstatusSeguidor;
    }

    public void setIdEstatusSeguidor(int idEstatusSeguidor) {
        this.idEstatusSeguidor = idEstatusSeguidor;
    }

    @Column(name = "nombre_estatus_seguidor", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreEstatusSeguidor() {
        return this.nombreEstatusSeguidor;
    }

    public void setNombreEstatusSeguidor(String nombreEstatusSeguidor) {
        this.nombreEstatusSeguidor = nombreEstatusSeguidor;
    }

    @Column(name = "definicion_estatus_seguidor", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionEstatusSeguidor() {
        return this.definicionEstatusSeguidor;
    }

    public void setDefinicionEstatusSeguidor(String definicionEstatusSeguidor) {
        this.definicionEstatusSeguidor = definicionEstatusSeguidor;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatusSeguidor")
    public Set<Seguidor> getSeguidors() {
        return this.seguidors;
    }

    public void setSeguidors(Set<Seguidor> seguidors) {
        this.seguidors = seguidors;
    }
}
