package mx.uam.azc.link.model;
// Generated 13/07/2011 12:55:13 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Idea generated by hbm2java
 */
@Entity
@Table(name = "idea")
public class Idea implements java.io.Serializable {

	private int idIdea;
	private Lugar lugar;
	private EstatusIdea estatusIdea;
	private Usuario usuario;
	private EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos;
	private EstatusAyudaMonetaria estatusAyudaMonetaria;
	private String tituloIdea;
	private Date fechaCreacionIdea;
	private String resumenIdea;
	private String nombreImagen;
	private int votosPositivosIdea;
	private int votosNegativosIdea;
	private Double calificacionIdea;
	private String contenidoIdea;
	private Set<Necesidad> necesidads = new HashSet<Necesidad>(0);
	private Set<Justificacion> justificacions = new HashSet<Justificacion>(0);
	private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);
	private Set<ComoLograrlo> comoLograrlos = new HashSet<ComoLograrlo>(0);
	private Set<ObjetivoGeneral> objetivoGenerals = 
                new HashSet<ObjetivoGeneral>(0);
	private Set<Integrante> integrantes = new HashSet<Integrante>(0);
	private Set<ClasificacionIdea> clasificacionIdeas =
                new HashSet<ClasificacionIdea>(0);
	private Set<ReporteAbuso> reporteAbusos = new HashSet<ReporteAbuso>(0);
        private Set<Envio> envios = new HashSet<Envio>(0);
	private Set<Seguidor> seguidors = new HashSet<Seguidor>(0);
	private Set<Imagen> imagens = new HashSet<Imagen>(0);
	private Set<Aviso> avisos = new HashSet<Aviso>(0);
	private Set<ObjetivoEspecifico> objetivoEspecificos =
                new HashSet<ObjetivoEspecifico>(0);
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<Pregunta> preguntas = new HashSet<Pregunta>(0);

	public Idea() {
	}

public Idea(int idIdea, EstatusIdea estatusIdea, Usuario usuario,
            EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
            EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
            Date fechaCreacionIdea, String resumenIdea, int votosPositivosIdea,
            int votosNegativosIdea, String contenidoIdea) {
            this.idIdea = idIdea;
            this.estatusIdea = estatusIdea;
            this.usuario = usuario;
            this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
            this.estatusAyudaMonetaria = estatusAyudaMonetaria;
            this.tituloIdea = tituloIdea;
            this.fechaCreacionIdea = fechaCreacionIdea;
            this.resumenIdea = resumenIdea;
            this.votosPositivosIdea = votosPositivosIdea;
            this.votosNegativosIdea = votosNegativosIdea;
            this.contenidoIdea = contenidoIdea;
        }

        public Idea(int idIdea, EstatusIdea estatusIdea, Usuario usuario,
            EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
            EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
            Date fechaCreacionIdea, String resumenIdea, String nombreImagen,
            int votosPositivosIdea, int votosNegativosIdea,
            Double calificacionIdea, String contenidoIdea,
            Set<Necesidad> necesidads, Set<Justificacion> justificacions,
            Set<Bitacora> bitacoras, Set<ComoLograrlo> comoLograrlos,
            Set<ObjetivoGeneral> objetivoGenerals, Set<Integrante> integrantes,
            Set<ClasificacionIdea> clasificacionIdeas,
            Set<ReporteAbuso> reporteAbusos, Set<Envio> envios,
            Set<Seguidor> seguidors, Set<Imagen> imagens,
            Set<ObjetivoEspecifico> objetivoEspecificos
            , Set<Pregunta> preguntas) {
        this.idIdea = idIdea;
        this.estatusIdea = estatusIdea;
        this.usuario = usuario;
        this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
        this.estatusAyudaMonetaria = estatusAyudaMonetaria;
        this.tituloIdea = tituloIdea;
        this.fechaCreacionIdea = fechaCreacionIdea;
        this.resumenIdea = resumenIdea;
        this.nombreImagen = nombreImagen;
        this.votosPositivosIdea = votosPositivosIdea;
        this.votosNegativosIdea = votosNegativosIdea;
        this.calificacionIdea = calificacionIdea;
        this.contenidoIdea = contenidoIdea;
        this.necesidads = necesidads;
        this.justificacions = justificacions;
        this.bitacoras = bitacoras;
        this.comoLograrlos = comoLograrlos;
        this.objetivoGenerals = objetivoGenerals;
        this.integrantes = integrantes;
        this.clasificacionIdeas = clasificacionIdeas;
        this.reporteAbusos = reporteAbusos;
        this.envios = envios;
        this.seguidors = seguidors;
        this.imagens = imagens;
        this.objetivoEspecificos = objetivoEspecificos;
        this.preguntas = preguntas;
    }

        public Idea(int idIdea, EstatusIdea estatusIdea, Usuario usuario,
            EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
            EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
            Date fechaCreacionIdea, String resumenIdea, String nombreImagen,
            int votosPositivosIdea, int votosNegativosIdea,
            Double calificacionIdea, String contenidoIdea, Boolean activa,
            Set<Necesidad> necesidads, Set<Justificacion> justificacions,
            Set<Bitacora> bitacoras, Set<ComoLograrlo> comoLograrlos,
            Set<ObjetivoGeneral> objetivoGenerals, Set<Integrante> integrantes,
            Set<ClasificacionIdea> clasificacionIdeas,
            Set<ReporteAbuso> reporteAbusos, Set<Seguidor> seguidors,
            Set<Envio> envios, Set<Imagen> imagens, Set<Aviso> avisos,
            Set<ObjetivoEspecifico> objetivoEspecificos
            , Set<Pregunta> preguntas) {
        this.idIdea = idIdea;
        this.estatusIdea = estatusIdea;
        this.usuario = usuario;
        this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
        this.estatusAyudaMonetaria = estatusAyudaMonetaria;
        this.tituloIdea = tituloIdea;
        this.fechaCreacionIdea = fechaCreacionIdea;
        this.resumenIdea = resumenIdea;
        this.nombreImagen = nombreImagen;
        this.votosPositivosIdea = votosPositivosIdea;
        this.votosNegativosIdea = votosNegativosIdea;
        this.calificacionIdea = calificacionIdea;
        this.contenidoIdea = contenidoIdea;
        this.necesidads = necesidads;
        this.justificacions = justificacions;
        this.bitacoras = bitacoras;
        this.comoLograrlos = comoLograrlos;
        this.objetivoGenerals = objetivoGenerals;
        this.integrantes = integrantes;
        this.clasificacionIdeas = clasificacionIdeas;
        this.reporteAbusos = reporteAbusos;
        this.seguidors = seguidors;
        this.envios = envios;
        this.imagens = imagens;
        this.avisos = avisos;
        this.objetivoEspecificos = objetivoEspecificos;
        this.preguntas = preguntas;
    }

	public Idea(int idIdea, EstatusIdea estatusIdea, Usuario usuario,
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
			EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
			Date fechaCreacionIdea, int votosPositivosIdea,
			int votosNegativosIdea, String contenidoIdea) {
		this.idIdea = idIdea;
		this.estatusIdea = estatusIdea;
		this.usuario = usuario;
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
		this.estatusAyudaMonetaria = estatusAyudaMonetaria;
		this.tituloIdea = tituloIdea;
		this.fechaCreacionIdea = fechaCreacionIdea;
		this.votosPositivosIdea = votosPositivosIdea;
		this.votosNegativosIdea = votosNegativosIdea;
		this.contenidoIdea = contenidoIdea;
	}
        public Idea(int idIdea, Lugar lugar, EstatusIdea estatusIdea,
			Usuario usuario,
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
			EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
			Date fechaCreacionIdea, String resumenIdea, String nombreImagen,
			int votosPositivosIdea, int votosNegativosIdea,
			Double calificacionIdea, String contenidoIdea,
			Set<Necesidad> necesidads, Set<Justificacion> justificacions,
			Set<Bitacora> bitacoras, Set<ComoLograrlo> comoLograrlos,
			Set<ObjetivoGeneral> objetivoGenerals, Set<Integrante> integrantes,
			Set<ClasificacionIdea> clasificacionIdeas,
			Set<ReporteAbuso> reporteAbusos, Set<Seguidor> seguidors,
			Set<Envio> envios, Set<Imagen> imagens, Set<Aviso> avisos,
			Set<ObjetivoEspecifico> objetivoEspecificos, Set<Pregunta> preguntas) {
		this.idIdea = idIdea;
		this.lugar = lugar;
		this.estatusIdea = estatusIdea;
		this.usuario = usuario;
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
		this.estatusAyudaMonetaria = estatusAyudaMonetaria;
		this.tituloIdea = tituloIdea;
		this.fechaCreacionIdea = fechaCreacionIdea;
		this.resumenIdea = resumenIdea;
		this.nombreImagen = nombreImagen;
		this.votosPositivosIdea = votosPositivosIdea;
		this.votosNegativosIdea = votosNegativosIdea;
		this.calificacionIdea = calificacionIdea;
		this.contenidoIdea = contenidoIdea;
		this.necesidads = necesidads;
		this.justificacions = justificacions;
		this.bitacoras = bitacoras;
		this.comoLograrlos = comoLograrlos;
		this.objetivoGenerals = objetivoGenerals;
		this.integrantes = integrantes;
		this.clasificacionIdeas = clasificacionIdeas;
		this.reporteAbusos = reporteAbusos;
		this.seguidors = seguidors;
		this.envios = envios;
		this.imagens = imagens;
		this.avisos = avisos;
		this.objetivoEspecificos = objetivoEspecificos;
		this.preguntas = preguntas;
	}
	public Idea(int idIdea, Lugar lugar, EstatusIdea estatusIdea,
			Usuario usuario,
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
			EstatusAyudaMonetaria estatusAyudaMonetaria, String tituloIdea,
			Date fechaCreacionIdea, String resumenIdea, String nombreImagen,
			int votosPositivosIdea, int votosNegativosIdea,
			Double calificacionIdea, String contenidoIdea,
			Set<Necesidad> necesidads, Set<Justificacion> justificacions,
			Set<Bitacora> bitacoras, Set<ComoLograrlo> comoLograrlos,
			Set<ObjetivoGeneral> objetivoGenerals, Set<Integrante> integrantes,
			Set<ClasificacionIdea> clasificacionIdeas,
			Set<ReporteAbuso> reporteAbusos, Set<Seguidor> seguidors,
			Set<Envio> envios, Set<Imagen> imagens, Set<Aviso> avisos,
			Set<ObjetivoEspecifico> objetivoEspecificos, Set<Visita> visitas,
			Set<Pregunta> preguntas) {
		this.idIdea = idIdea;
		this.lugar = lugar;
		this.estatusIdea = estatusIdea;
		this.usuario = usuario;
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
		this.estatusAyudaMonetaria = estatusAyudaMonetaria;
		this.tituloIdea = tituloIdea;
		this.fechaCreacionIdea = fechaCreacionIdea;
		this.resumenIdea = resumenIdea;
		this.nombreImagen = nombreImagen;
		this.votosPositivosIdea = votosPositivosIdea;
		this.votosNegativosIdea = votosNegativosIdea;
		this.calificacionIdea = calificacionIdea;
		this.contenidoIdea = contenidoIdea;
		this.necesidads = necesidads;
		this.justificacions = justificacions;
		this.bitacoras = bitacoras;
		this.comoLograrlos = comoLograrlos;
		this.objetivoGenerals = objetivoGenerals;
		this.integrantes = integrantes;
		this.clasificacionIdeas = clasificacionIdeas;
		this.reporteAbusos = reporteAbusos;
		this.seguidors = seguidors;
		this.envios = envios;
		this.imagens = imagens;
		this.avisos = avisos;
		this.objetivoEspecificos = objetivoEspecificos;
		this.visitas = visitas;
		this.preguntas = preguntas;
	}
	


	@Id
	@Column(name = "id_idea", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	public int getIdIdea() {
		return this.idIdea;
	}

	public void setIdIdea(int idIdea) {
		this.idIdea = idIdea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lugar_id")
	public Lugar getLugar() {
		return this.lugar;
	}

	public void setLugar(Lugar lugar) {
		this.lugar = lugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_idea_id", nullable = false)
	@NotNull
	public EstatusIdea getEstatusIdea() {
		return this.estatusIdea;
	}

	public void setEstatusIdea(EstatusIdea estatusIdea) {
		this.estatusIdea = estatusIdea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_ayuda_recursos_humanos_id", nullable = false)
	@NotNull
	public EstatusAyudaRecursosHumanos getEstatusAyudaRecursosHumanos() {
		return this.estatusAyudaRecursosHumanos;
	}

	public void setEstatusAyudaRecursosHumanos(
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos) {
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_ayuda_monetaria_id", nullable = false)
	@NotNull
	public EstatusAyudaMonetaria getEstatusAyudaMonetaria() {
		return this.estatusAyudaMonetaria;
	}

	public void setEstatusAyudaMonetaria(
			EstatusAyudaMonetaria estatusAyudaMonetaria) {
		this.estatusAyudaMonetaria = estatusAyudaMonetaria;
	}

	@Column(name = "titulo_idea", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getTituloIdea() {
		return this.tituloIdea;
	}

	public void setTituloIdea(String tituloIdea) {
		this.tituloIdea = tituloIdea;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creacion_idea", nullable = false, length = 13)
	@NotNull
	public Date getFechaCreacionIdea() {
		return this.fechaCreacionIdea;
	}

	public void setFechaCreacionIdea(Date fechaCreacionIdea) {
		this.fechaCreacionIdea = fechaCreacionIdea;
	}

	@Column(name = "resumen_idea", length = 500)
    @Length(max = 500, message = "#{messages['idea.crear.resumen.error.longitudmax']}")
	public String getResumenIdea() {
		return this.resumenIdea;
	}

	public void setResumenIdea(String resumenIdea) {
		this.resumenIdea = resumenIdea;
	}

	@Column(name = "nombre_imagen", length = 100)
	@Length(max = 100)
	public String getNombreImagen() {
		return this.nombreImagen;
	}

	public void setNombreImagen(String nombreImagen) {
		this.nombreImagen = nombreImagen;
	}

	@Column(name = "votos_positivos_idea", nullable = false)
	public int getVotosPositivosIdea() {
		return this.votosPositivosIdea;
	}

	public void setVotosPositivosIdea(int votosPositivosIdea) {
		this.votosPositivosIdea = votosPositivosIdea;
	}

	@Column(name = "votos_negativos_idea", nullable = false)
	public int getVotosNegativosIdea() {
		return this.votosNegativosIdea;
	}

	public void setVotosNegativosIdea(int votosNegativosIdea) {
		this.votosNegativosIdea = votosNegativosIdea;
	}

	@Column(name = "calificacion_idea", precision = 17, scale = 17)
	public Double getCalificacionIdea() {
		return this.calificacionIdea;
	}

	public void setCalificacionIdea(Double calificacionIdea) {
		this.calificacionIdea = calificacionIdea;
	}

	@Column(name = "contenido_idea", nullable = false, length = 20000)
	@NotNull
	@Length(max = 20000)
	public String getContenidoIdea() {
		return this.contenidoIdea;
	}

	public void setContenidoIdea(String contenidoIdea) {
		this.contenidoIdea = contenidoIdea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Necesidad> getNecesidads() {
		return this.necesidads;
	}

	public void setNecesidads(Set<Necesidad> necesidads) {
		this.necesidads = necesidads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Justificacion> getJustificacions() {
		return this.justificacions;
	}

	public void setJustificacions(Set<Justificacion> justificacions) {
		this.justificacions = justificacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Bitacora> getBitacoras() {
		return this.bitacoras;
	}

	public void setBitacoras(Set<Bitacora> bitacoras) {
		this.bitacoras = bitacoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<ComoLograrlo> getComoLograrlos() {
		return this.comoLograrlos;
	}

	public void setComoLograrlos(Set<ComoLograrlo> comoLograrlos) {
		this.comoLograrlos = comoLograrlos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<ObjetivoGeneral> getObjetivoGenerals() {
		return this.objetivoGenerals;
	}

	public void setObjetivoGenerals(Set<ObjetivoGeneral> objetivoGenerals) {
		this.objetivoGenerals = objetivoGenerals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Integrante> getIntegrantes() {
		return this.integrantes;
	}

	public void setIntegrantes(Set<Integrante> integrantes) {
		this.integrantes = integrantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<ClasificacionIdea> getClasificacionIdeas() {
		return this.clasificacionIdeas;
	}

    public void setClasificacionIdeas
                                   (Set<ClasificacionIdea> clasificacionIdeas) {
		this.clasificacionIdeas = clasificacionIdeas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<ReporteAbuso> getReporteAbusos() {
		return this.reporteAbusos;
	}

	public void setReporteAbusos(Set<ReporteAbuso> reporteAbusos) {
		this.reporteAbusos = reporteAbusos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Seguidor> getSeguidors() {
		return this.seguidors;
	}

	public void setSeguidors(Set<Seguidor> seguidors) {
		this.seguidors = seguidors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Envio> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<Envio> envios) {
		this.envios = envios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Imagen> getImagens() {
		return this.imagens;
	}

	public void setImagens(Set<Imagen> imagens) {
		this.imagens = imagens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<ObjetivoEspecifico> getObjetivoEspecificos() {
		return this.objetivoEspecificos;
	}

	public void setObjetivoEspecificos(
			Set<ObjetivoEspecifico> objetivoEspecificos) {
		this.objetivoEspecificos = objetivoEspecificos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idea")
	public Set<Pregunta> getPreguntas() {
		return this.preguntas;
	}

	public void setPreguntas(Set<Pregunta> preguntas) {
		this.preguntas = preguntas;
	}

    public boolean isActiva() {
        return getEstatusIdea().getIdEstatusIdea() == 1 ? true : false;
}

    public void setActiva(Boolean activa) {
        //this.activa = activa;
    }
}
