package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name = "imagen")
public class Imagen implements java.io.Serializable {

    private int idImagen;
    private Idea idea;
    private String nombreImagen;

    public Imagen() {
    }

    public Imagen(int idImagen, Idea idea, String nombreImagen) {
        this.idImagen = idImagen;
        this.idea = idea;
        this.nombreImagen = nombreImagen;
    }

    public Imagen(Idea idea, String nombreImagen) {
        this.idea = idea;
        this.nombreImagen = nombreImagen;
    }

    @Id
    @Column(name = "id_imagen", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdImagen() {
        return this.idImagen;
    }

    public void setIdImagen(int idImagen) {
        this.idImagen = idImagen;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "nombre_imagen", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreImagen() {
        return this.nombreImagen;
    }

    public void setNombreImagen(String nombreImagen) {
        this.nombreImagen = nombreImagen;
    }
}
