package mx.uam.azc.link.model;
// Generated 13/07/2011 12:55:13 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Institucion generated by hbm2java
 */
@Entity
@Table(name = "institucion")
public class Institucion implements java.io.Serializable {

    private Integer idInstitucion;
	private String nombreInstitucion;
	private String descripcionInstitucion;
	private String urlInstitucion;
	private String nombreImagenInstitucion;
	private Set<Visita> visitas = new HashSet<Visita>(0);
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Institucion() {
	}

    public Institucion(Integer idInstitucion, String nombreInstitucion,
			String descripcionInstitucion) {
		this.idInstitucion = idInstitucion;
		this.nombreInstitucion = nombreInstitucion;
		this.descripcionInstitucion = descripcionInstitucion;
	}

         public Institucion(Integer idInstitucion, String nombreInstitucion,
            String descripcionInstitucion, String urlInstitucion,
            String nombreImagenInstitucion, Set<Usuario> usuarios) {
        this.idInstitucion = idInstitucion;
        this.nombreInstitucion = nombreInstitucion;
        this.descripcionInstitucion = descripcionInstitucion;
        this.urlInstitucion = urlInstitucion;
        this.nombreImagenInstitucion = nombreImagenInstitucion;
        this.usuarios = usuarios;
    }
	public Institucion(int idInstitucion, String nombreInstitucion,
			String descripcionInstitucion, String urlInstitucion,
			String nombreImagenInstitucion, Set<Visita> visitas,
			Set<Usuario> usuarios) {
		this.idInstitucion = idInstitucion;
		this.nombreInstitucion = nombreInstitucion;
		this.descripcionInstitucion = descripcionInstitucion;
		this.urlInstitucion = urlInstitucion;
		this.nombreImagenInstitucion = nombreImagenInstitucion;
		this.visitas = visitas;
		this.usuarios = usuarios;
	}

	@Id
	@Column(name = "id_institucion", unique = true, nullable = false)
    public Integer getIdInstitucion() {
		return this.idInstitucion;
	}

    public void setIdInstitucion(Integer idInstitucion) {
		this.idInstitucion = idInstitucion;
	}

	@Column(name = "nombre_institucion", nullable = false, length = 70)
	@NotNull
	@Length(max = 70)
	public String getNombreInstitucion() {
		return this.nombreInstitucion;
	}

	public void setNombreInstitucion(String nombreInstitucion) {
		this.nombreInstitucion = nombreInstitucion;
	}

	@Column(name = "descripcion_institucion", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getDescripcionInstitucion() {
		return this.descripcionInstitucion;
	}

	public void setDescripcionInstitucion(String descripcionInstitucion) {
		this.descripcionInstitucion = descripcionInstitucion;
	}

	@Column(name = "url_institucion", length = 100)
	@Length(max = 100)
	public String getUrlInstitucion() {
		return this.urlInstitucion;
	}

	public void setUrlInstitucion(String urlInstitucion) {
		this.urlInstitucion = urlInstitucion;
	}

	@Column(name = "nombre_imagen_institucion", length = 100)
	@Length(max = 100)
	public String getNombreImagenInstitucion() {
		return this.nombreImagenInstitucion;
	}

	public void setNombreImagenInstitucion(String nombreImagenInstitucion) {
		this.nombreImagenInstitucion = nombreImagenInstitucion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institucion")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "institucion")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
