package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IntegranteId generated by hbm2java
 */
@Embeddable
public class IntegranteId implements java.io.Serializable {

    private int usuarioId;
    private int ideaId;

    public IntegranteId() {
    }

    public IntegranteId(int usuarioId, int ideaId) {
        this.usuarioId = usuarioId;
        this.ideaId = ideaId;
    }

    @Column(name = "usuario_id", nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @Column(name = "idea_id", nullable = false)
    public int getIdeaId() {
        return this.ideaId;
    }

    public void setIdeaId(int ideaId) {
        this.ideaId = ideaId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof IntegranteId)) {
            return false;
        }
        IntegranteId castOther = (IntegranteId) other;

        return (this.getUsuarioId() == castOther.getUsuarioId())
                && (this.getIdeaId() == castOther.getIdeaId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUsuarioId();
        result = 37 * result + this.getIdeaId();
        return result;
    }
}
