package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Justificacion generated by hbm2java
 */
@Entity
@Table(name = "justificacion")
public class Justificacion implements java.io.Serializable {

    private int idJustificacion;
    private Idea idea;
    private String descripcionJustificacion;
    private Date fechaJustificacion;

    public Justificacion() {
    }

    public Justificacion(int idJustificacion, Idea idea,
            String descripcionJustificacion) {
        this.idJustificacion = idJustificacion;
        this.idea = idea;
        this.descripcionJustificacion = descripcionJustificacion;
    }

    public Justificacion(int idJustificacion, Idea idea,
            String descripcionJustificacion, Date fechaJustificacion) {
        this.idJustificacion = idJustificacion;
        this.idea = idea;
        this.descripcionJustificacion = descripcionJustificacion;
        this.fechaJustificacion = fechaJustificacion;
    }

    @Id
    @Column(name = "id_justificacion", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdJustificacion() {
        return this.idJustificacion;
    }

    public void setIdJustificacion(int idJustificacion) {
        this.idJustificacion = idJustificacion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "descripcion_justificacion", nullable = false, length = 500)
    @NotNull
    @Length(max = 500)
    public String getDescripcionJustificacion() {
        return this.descripcionJustificacion;
    }

    public void setDescripcionJustificacion(String descripcionJustificacion) {
        this.descripcionJustificacion = descripcionJustificacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_justificacion", length = 13)
    public Date getFechaJustificacion() {
        return this.fechaJustificacion;
    }

    public void setFechaJustificacion(Date fechaJustificacion) {
        this.fechaJustificacion = fechaJustificacion;
    }
}
