package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Lugar generated by hbm2java
 */
@Entity
@Table(name = "lugar")
public class Lugar implements java.io.Serializable {

	private int idLugar;
	private TipoLugar tipoLugar;
	private Usuario usuario;
	private String nombreLugar;
	private String descripcionLugar;
	private Set<Idea> ideas = new HashSet<Idea>(0);

	public Lugar() {
	}

	public Lugar(int idLugar, TipoLugar tipoLugar, String nombreLugar,
			String descripcionLugar) {
		this.idLugar = idLugar;
		this.tipoLugar = tipoLugar;
		this.nombreLugar = nombreLugar;
		this.descripcionLugar = descripcionLugar;
	}
	public Lugar(int idLugar, TipoLugar tipoLugar, Usuario usuario,
			String nombreLugar, String descripcionLugar, Set<Idea> ideas) {
		this.idLugar = idLugar;
		this.tipoLugar = tipoLugar;
		this.usuario = usuario;
		this.nombreLugar = nombreLugar;
		this.descripcionLugar = descripcionLugar;
		this.ideas = ideas;
	}

	@Id
	@Column(name = "id_lugar", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(int idLugar) {
		this.idLugar = idLugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_lugar_id", nullable = false)
	@NotNull
	public TipoLugar getTipoLugar() {
		return this.tipoLugar;
	}

	public void setTipoLugar(TipoLugar tipoLugar) {
		this.tipoLugar = tipoLugar;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre_lugar", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNombreLugar() {
		return this.nombreLugar;
	}

	public void setNombreLugar(String nombreLugar) {
		this.nombreLugar = nombreLugar;
	}

	@Column(name = "descripcion_lugar", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionLugar() {
		return this.descripcionLugar;
	}

	public void setDescripcionLugar(String descripcionLugar) {
		this.descripcionLugar = descripcionLugar;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lugar")
	public Set<Idea> getIdeas() {
		return this.ideas;
	}

	public void setIdeas(Set<Idea> ideas) {
		this.ideas = ideas;
	}

}
