package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MiembroComunidadId generated by hbm2java
 */
@Embeddable
public class MiembroComunidadId implements java.io.Serializable {

    private int usuarioId;
    private int comunidadId;

    public MiembroComunidadId() {
    }

    public MiembroComunidadId(int usuarioId, int comunidadId) {
        this.usuarioId = usuarioId;
        this.comunidadId = comunidadId;
    }

    @Column(name = "usuario_id", nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @Column(name = "comunidad_id", nullable = false)
    public int getComunidadId() {
        return this.comunidadId;
    }

    public void setComunidadId(int comunidadId) {
        this.comunidadId = comunidadId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof MiembroComunidadId)) {
            return false;
        }
        MiembroComunidadId castOther = (MiembroComunidadId) other;

        return (this.getUsuarioId() == castOther.getUsuarioId())
                && (this.getComunidadId() == castOther.getComunidadId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUsuarioId();
        result = 37 * result + this.getComunidadId();
        return result;
    }
}
