package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * MiembroComunidad generated by hbm2java
 */
@Entity
@Table(name = "miembro_comunidad")
public class MiembroComunidad implements java.io.Serializable {

    private MiembroComunidadId id;
    private Comunidad comunidad;
    private Usuario usuario;
    private EstatusMiembroComunidad estatusMiembroComunidad;
    private Date fechaInicioMiembroComunidad;
    private Date fechaFinMiembroComunidad;

    public MiembroComunidad() {
    }

    public MiembroComunidad(MiembroComunidadId id, Comunidad comunidad,
            Usuario usuario, EstatusMiembroComunidad estatusMiembroComunidad,
            Date fechaInicioMiembroComunidad) {
        this.id = id;
        this.comunidad = comunidad;
        this.usuario = usuario;
        this.estatusMiembroComunidad = estatusMiembroComunidad;
        this.fechaInicioMiembroComunidad = fechaInicioMiembroComunidad;
    }

    public MiembroComunidad(MiembroComunidadId id, Comunidad comunidad,
            Usuario usuario, EstatusMiembroComunidad estatusMiembroComunidad,
            Date fechaInicioMiembroComunidad, Date fechaFinMiembroComunidad) {
        this.id = id;
        this.comunidad = comunidad;
        this.usuario = usuario;
        this.estatusMiembroComunidad = estatusMiembroComunidad;
        this.fechaInicioMiembroComunidad = fechaInicioMiembroComunidad;
        this.fechaFinMiembroComunidad = fechaFinMiembroComunidad;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "usuarioId", column =
        @Column(name = "usuario_id", nullable = false)),
        @AttributeOverride(name = "comunidadId", column =
        @Column(name = "comunidad_id", nullable = false))})
    @NotNull
    public MiembroComunidadId getId() {
        return this.id;
    }

    public void setId(MiembroComunidadId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "comunidad_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Comunidad getComunidad() {
        return this.comunidad;
    }

    public void setComunidad(Comunidad comunidad) {
        this.comunidad = comunidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus_miembro_comunidad_id", nullable = false)
    @NotNull
    public EstatusMiembroComunidad getEstatusMiembroComunidad() {
        return this.estatusMiembroComunidad;
    }

    public void setEstatusMiembroComunidad(
            EstatusMiembroComunidad estatusMiembroComunidad) {
        this.estatusMiembroComunidad = estatusMiembroComunidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicio_miembro_comunidad", nullable = false, length = 13)
    @NotNull
    public Date getFechaInicioMiembroComunidad() {
        return this.fechaInicioMiembroComunidad;
    }

    public void setFechaInicioMiembroComunidad
                                            (Date fechaInicioMiembroComunidad) {
        this.fechaInicioMiembroComunidad = fechaInicioMiembroComunidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_fin_miembro_comunidad", length = 13)
    public Date getFechaFinMiembroComunidad() {
        return this.fechaFinMiembroComunidad;
    }

    public void setFechaFinMiembroComunidad(Date fechaFinMiembroComunidad) {
        this.fechaFinMiembroComunidad = fechaFinMiembroComunidad;
    }
}
