package mx.uam.azc.link.model;
// Generated 8/04/2011 07:14:19 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Necesidad generated by hbm2java
 */
@Entity
@Table(name = "necesidad")
public class Necesidad implements java.io.Serializable {

    private int idNecesidad;
    private EstatusNecesidad estatusNecesidad;
    private Idea idea;
    private String descripcionNecesidad;
    private Date fechaNecesidad;
    private Set<Canica> canicas = new HashSet<Canica>(0);

    public Necesidad() {
    }

    public Necesidad(int idNecesidad, EstatusNecesidad estatusNecesidad,
            Idea idea, String descripcionNecesidad) {
        this.idNecesidad = idNecesidad;
        this.estatusNecesidad = estatusNecesidad;
        this.idea = idea;
        this.descripcionNecesidad = descripcionNecesidad;
    }

    public Necesidad(int idNecesidad, EstatusNecesidad estatusNecesidad,
            Idea idea, String descripcionNecesidad, Date fechaNecesidad,
            Set<Canica> canicas) {
        this.idNecesidad = idNecesidad;
        this.estatusNecesidad = estatusNecesidad;
        this.idea = idea;
        this.descripcionNecesidad = descripcionNecesidad;
        this.fechaNecesidad = fechaNecesidad;
        this.canicas = canicas;
    }

    public Necesidad(EstatusNecesidad estatusNecesidad, Idea idea
            , String descripcionNecesidad, java.sql.Date fechaNecesidad) {
        this.estatusNecesidad = estatusNecesidad;
        this.idea = idea;
        this.descripcionNecesidad = descripcionNecesidad;
        this.fechaNecesidad = fechaNecesidad;
    }

    @Id
    @Column(name = "id_necesidad", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdNecesidad() {
        return this.idNecesidad;
    }

    public void setIdNecesidad(int idNecesidad) {
        this.idNecesidad = idNecesidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus_necesidad_id", nullable = false)
    @NotNull
    public EstatusNecesidad getEstatusNecesidad() {
        return this.estatusNecesidad;
    }

    public void setEstatusNecesidad(EstatusNecesidad estatusNecesidad) {
        this.estatusNecesidad = estatusNecesidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "descripcion_necesidad", nullable = false, length = 500)
    @NotNull
    @Length(max = 500)
    public String getDescripcionNecesidad() {
        return this.descripcionNecesidad;
    }

    public void setDescripcionNecesidad(String descripcionNecesidad) {
        this.descripcionNecesidad = descripcionNecesidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_necesidad", length = 13)
    public Date getFechaNecesidad() {
        return this.fechaNecesidad;
    }

    public void setFechaNecesidad(Date fechaNecesidad) {
        this.fechaNecesidad = fechaNecesidad;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "necesidad")
    public Set<Canica> getCanicas() {
        return this.canicas;
    }

    public void setCanicas(Set<Canica> canicas) {
        this.canicas = canicas;
    }
}
