package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ObjetivoGeneral generated by hbm2java
 */
@Entity
@Table(name = "objetivo_general")
public class ObjetivoGeneral implements java.io.Serializable {

    private int idObjetivoGeneral;
    private Idea idea;
    private String descripcionObjetivoGeneral;
    private Date fechaObjetivoGeneral;

    public ObjetivoGeneral() {
    }

    public ObjetivoGeneral(int idObjetivoGeneral, Idea idea,
            String descripcionObjetivoGeneral) {
        this.idObjetivoGeneral = idObjetivoGeneral;
        this.idea = idea;
        this.descripcionObjetivoGeneral = descripcionObjetivoGeneral;
    }

    public ObjetivoGeneral(int idObjetivoGeneral, Idea idea,
            String descripcionObjetivoGeneral, Date fechaObjetivoGeneral) {
        this.idObjetivoGeneral = idObjetivoGeneral;
        this.idea = idea;
        this.descripcionObjetivoGeneral = descripcionObjetivoGeneral;
        this.fechaObjetivoGeneral = fechaObjetivoGeneral;
    }

    @Id
    @Column(name = "id_objetivo_general", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdObjetivoGeneral() {
        return this.idObjetivoGeneral;
    }

    public void setIdObjetivoGeneral(int idObjetivoGeneral) {
        this.idObjetivoGeneral = idObjetivoGeneral;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "descripcion_objetivo_general", nullable = false, length = 250)
    @NotNull
    @Length(max = 250)
    public String getDescripcionObjetivoGeneral() {
        return this.descripcionObjetivoGeneral;
    }

    public void setDescripcionObjetivoGeneral
                                           (String descripcionObjetivoGeneral) {
        this.descripcionObjetivoGeneral = descripcionObjetivoGeneral;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_objetivo_general", length = 13)
    public Date getFechaObjetivoGeneral() {
        return this.fechaObjetivoGeneral;
    }

    public void setFechaObjetivoGeneral(Date fechaObjetivoGeneral) {
        this.fechaObjetivoGeneral = fechaObjetivoGeneral;
    }
}
