package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ObjetivoEspecifico generated by hbm2java
 */
@Entity
@Table(name = "objetivo_especifico")
public class ObjetivoEspecifico implements java.io.Serializable {

    private int idObjetivoEspecifico;
    private Idea idea;
    private String descripcionObjetivoEspecifico;
    private Date fechaObjetivoEspecifico;

    public ObjetivoEspecifico() {
    }

    public ObjetivoEspecifico(int idObjetivoEspecifico, Idea idea,
            String descripcionObjetivoEspecifico) {
        this.idObjetivoEspecifico = idObjetivoEspecifico;
        this.idea = idea;
        this.descripcionObjetivoEspecifico = descripcionObjetivoEspecifico;
    }

    public ObjetivoEspecifico(int idObjetivoEspecifico, Idea idea,
            String descripcionObjetivoEspecifico
            , Date fechaObjetivoEspecifico) {
        this.idObjetivoEspecifico = idObjetivoEspecifico;
        this.idea = idea;
        this.descripcionObjetivoEspecifico = descripcionObjetivoEspecifico;
        this.fechaObjetivoEspecifico = fechaObjetivoEspecifico;
    }

    @Id
    @Column(name = "id_objetivo_especifico", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    public int getIdObjetivoEspecifico() {
        return this.idObjetivoEspecifico;
    }

    public void setIdObjetivoEspecifico(int idObjetivoEspecifico) {
        this.idObjetivoEspecifico = idObjetivoEspecifico;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @Column(name = "descripcion_objetivo_especifico", nullable = false, length = 250)
    @NotNull
    @Length(max = 250)
    public String getDescripcionObjetivoEspecifico() {
        return this.descripcionObjetivoEspecifico;
    }

    public void setDescripcionObjetivoEspecifico(
            String descripcionObjetivoEspecifico) {
        this.descripcionObjetivoEspecifico = descripcionObjetivoEspecifico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_objetivo_especifico", length = 13)
    public Date getFechaObjetivoEspecifico() {
        return this.fechaObjetivoEspecifico;
    }

    public void setFechaObjetivoEspecifico(Date fechaObjetivoEspecifico) {
        this.fechaObjetivoEspecifico = fechaObjetivoEspecifico;
    }
}
