package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermisoId generated by hbm2java
 */
@Embeddable
public class PermisoId implements java.io.Serializable {

    private int usuarioId;
    private int rolId;

    public PermisoId() {
    }

    public PermisoId(int usuarioId, int rolId) {
        this.usuarioId = usuarioId;
        this.rolId = rolId;
    }

    @Column(name = "usuario_id", nullable = false)
    public int getUsuarioId() {
        return this.usuarioId;
    }

    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    @Column(name = "rol_id", nullable = false)
    public int getRolId() {
        return this.rolId;
    }

    public void setRolId(int rolId) {
        this.rolId = rolId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PermisoId)) {
            return false;
        }
        PermisoId castOther = (PermisoId) other;

        return (this.getUsuarioId() == castOther.getUsuarioId())
                && (this.getRolId() == castOther.getRolId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getUsuarioId();
        result = 37 * result + this.getRolId();
        return result;
    }
}
