package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso")
public class Permiso implements java.io.Serializable {

    private PermisoId id;
    private Usuario usuario;
    private Rol rol;

    public Permiso() {
    }

    public Permiso(PermisoId id, Usuario usuario, Rol rol) {
        this.id = id;
        this.usuario = usuario;
        this.rol = rol;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "usuarioId", column =
        @Column(name = "usuario_id", nullable = false)),
        @AttributeOverride(name = "rolId", column =
        @Column(name = "rol_id", nullable = false))})
    @NotNull
    public PermisoId getId() {
        return this.id;
    }

    public void setId(PermisoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rol_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Rol getRol() {
        return this.rol;
    }

    public void setRol(Rol rol) {
        this.rol = rol;
    }
}
