package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * ReporteAbuso generated by hbm2java
 */
@Entity
@Table(name = "reporte_abuso")
public class ReporteAbuso implements java.io.Serializable {

	private int idReporteAbuso;
	private AccionReporteAbuso accionReporteAbuso;
	private Idea idea;
	private Usuario usuario;
	private EstatusReporteAbuso estatusReporteAbuso;
	private TipoReporteAbuso tipoReporteAbuso;
	private String notaReporteAbuso;
	private Date fechaReporteAbuso;
	private Set<Envio> envios = new HashSet<Envio>(0);
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public ReporteAbuso() {
	}

public ReporteAbuso(int idReporteAbuso, Idea idea,
            TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso) {
        this.idReporteAbuso = idReporteAbuso;
        this.idea = idea;
        this.tipoReporteAbuso = tipoReporteAbuso;
        this.notaReporteAbuso = notaReporteAbuso;
    }

    public ReporteAbuso(int idReporteAbuso, Idea idea, Usuario usuario,
            TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso) {
        this.idReporteAbuso = idReporteAbuso;
        this.idea = idea;
        this.usuario = usuario;
        this.tipoReporteAbuso = tipoReporteAbuso;
        this.notaReporteAbuso = notaReporteAbuso;
    }

    public ReporteAbuso(int idReporteAbuso, Idea idea,
            EstatusReporteAbuso estatusReporteAbuso,
            TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso,
            Date fechaReporteAbuso) {
        this.idReporteAbuso = idReporteAbuso;
        this.idea = idea;
        this.estatusReporteAbuso = estatusReporteAbuso;
        this.tipoReporteAbuso = tipoReporteAbuso;
        this.notaReporteAbuso = notaReporteAbuso;
        this.fechaReporteAbuso = fechaReporteAbuso;
    }

    public ReporteAbuso(int idReporteAbuso, Idea idea, Usuario usuario,
            EstatusReporteAbuso estatusReporteAbuso,
            TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso,
            Date fechaReporteAbuso, Set<Envio> envios, Set<Aviso> avisos) {
        this.idReporteAbuso = idReporteAbuso;
        this.idea = idea;
        this.usuario = usuario;
        this.estatusReporteAbuso = estatusReporteAbuso;
        this.tipoReporteAbuso = tipoReporteAbuso;
        this.notaReporteAbuso = notaReporteAbuso;
        this.fechaReporteAbuso = fechaReporteAbuso;
        this.envios = envios;
        this.avisos = avisos;
    }
	public ReporteAbuso(int idReporteAbuso,
			AccionReporteAbuso accionReporteAbuso, Idea idea,
			EstatusReporteAbuso estatusReporteAbuso,
			TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso,
			Date fechaReporteAbuso) {
		this.idReporteAbuso = idReporteAbuso;
		this.accionReporteAbuso = accionReporteAbuso;
		this.idea = idea;
		this.estatusReporteAbuso = estatusReporteAbuso;
		this.tipoReporteAbuso = tipoReporteAbuso;
		this.notaReporteAbuso = notaReporteAbuso;
		this.fechaReporteAbuso = fechaReporteAbuso;
	}
	public ReporteAbuso(int idReporteAbuso,
			AccionReporteAbuso accionReporteAbuso, Idea idea, Usuario usuario,
			EstatusReporteAbuso estatusReporteAbuso,
			TipoReporteAbuso tipoReporteAbuso, String notaReporteAbuso,
			Date fechaReporteAbuso, Set<Envio> envios, Set<Aviso> avisos) {
		this.idReporteAbuso = idReporteAbuso;
		this.accionReporteAbuso = accionReporteAbuso;
		this.idea = idea;
		this.usuario = usuario;
		this.estatusReporteAbuso = estatusReporteAbuso;
		this.tipoReporteAbuso = tipoReporteAbuso;
		this.notaReporteAbuso = notaReporteAbuso;
		this.fechaReporteAbuso = fechaReporteAbuso;
		this.envios = envios;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "id_reporte_abuso", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	public int getIdReporteAbuso() {
		return this.idReporteAbuso;
	}

	public void setIdReporteAbuso(int idReporteAbuso) {
		this.idReporteAbuso = idReporteAbuso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accion_reporte_abuso_id")
	public AccionReporteAbuso getAccionReporteAbuso() {
		return this.accionReporteAbuso;
	}

	public void setAccionReporteAbuso(AccionReporteAbuso accionReporteAbuso) {
		this.accionReporteAbuso = accionReporteAbuso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id", nullable = false)
	@NotNull
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_reporte_abuso_id", nullable = false)
	@NotNull
	public EstatusReporteAbuso getEstatusReporteAbuso() {
		return this.estatusReporteAbuso;
	}

    public void setEstatusReporteAbuso
                                     (EstatusReporteAbuso estatusReporteAbuso) {
		this.estatusReporteAbuso = estatusReporteAbuso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_reporte_abuso_id", nullable = false)
	@NotNull
	public TipoReporteAbuso getTipoReporteAbuso() {
		return this.tipoReporteAbuso;
	}

	public void setTipoReporteAbuso(TipoReporteAbuso tipoReporteAbuso) {
		this.tipoReporteAbuso = tipoReporteAbuso;
	}

	@Column(name = "nota_reporte_abuso", nullable = false, length = 1000)
	@NotNull
	@Length(max = 1000)
	public String getNotaReporteAbuso() {
		return this.notaReporteAbuso;
	}

	public void setNotaReporteAbuso(String notaReporteAbuso) {
		this.notaReporteAbuso = notaReporteAbuso;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_reporte_abuso", nullable = false, length = 13)
	@NotNull
	public Date getFechaReporteAbuso() {
		return this.fechaReporteAbuso;
	}

	public void setFechaReporteAbuso(Date fechaReporteAbuso) {
		this.fechaReporteAbuso = fechaReporteAbuso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteAbuso")
	public Set<Envio> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<Envio> envios) {
		this.envios = envios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "reporteAbuso")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}
}
