package mx.uam.azc.link.model;
// Generated 2/04/2011 10:45:34 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * Seguidor generated by hbm2java
 */
@Entity
@Table(name = "seguidor")
public class Seguidor implements java.io.Serializable {

    private SeguidorId id;
    private EstatusSeguidor estatusSeguidor;
    private Idea idea;
    private Usuario usuario;
    private Date fechaInicioSeguidor;
    private Date fechaFinSeguidor;

    public Seguidor() {
    }

    public Seguidor(SeguidorId id, EstatusSeguidor estatusSeguidor, Idea idea,
            Usuario usuario, Date fechaInicioSeguidor) {
        this.id = id;
        this.estatusSeguidor = estatusSeguidor;
        this.idea = idea;
        this.usuario = usuario;
        this.fechaInicioSeguidor = fechaInicioSeguidor;
    }

    public Seguidor(SeguidorId id, EstatusSeguidor estatusSeguidor, Idea idea,
            Usuario usuario, Date fechaInicioSeguidor, Date fechaFinSeguidor) {
        this.id = id;
        this.estatusSeguidor = estatusSeguidor;
        this.idea = idea;
        this.usuario = usuario;
        this.fechaInicioSeguidor = fechaInicioSeguidor;
        this.fechaFinSeguidor = fechaFinSeguidor;
    }

    public Seguidor(EstatusSeguidor estatusSeguidor, Idea idea, Usuario usuario, java.sql.Date fechaInicioSeguidor) {
        this.id = new SeguidorId(usuario.getIdUsuario(), idea.getIdIdea());
        this.estatusSeguidor = estatusSeguidor;
        this.idea = idea;
        this.usuario = usuario;
        this.fechaInicioSeguidor = fechaInicioSeguidor;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "usuarioId", column =
        @Column(name = "usuario_id", nullable = false)),
        @AttributeOverride(name = "ideaId", column =
        @Column(name = "idea_id", nullable = false))})
    @NotNull
    public SeguidorId getId() {
        return this.id;
    }

    public void setId(SeguidorId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus_seguidor_id", nullable = false)
    @NotNull
    public EstatusSeguidor getEstatusSeguidor() {
        return this.estatusSeguidor;
    }

    public void setEstatusSeguidor(EstatusSeguidor estatusSeguidor) {
        this.estatusSeguidor = estatusSeguidor;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idea_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Idea getIdea() {
        return this.idea;
    }

    public void setIdea(Idea idea) {
        this.idea = idea;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario_id", nullable = false, insertable = false, updatable = false)
    @NotNull
    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_inicio_seguidor", nullable = false, length = 13)
    @NotNull
    public Date getFechaInicioSeguidor() {
        return this.fechaInicioSeguidor;
    }

    public void setFechaInicioSeguidor(Date fechaInicioSeguidor) {
        this.fechaInicioSeguidor = fechaInicioSeguidor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fecha_fin_seguidor", length = 13)
    public Date getFechaFinSeguidor() {
        return this.fechaFinSeguidor;
    }

    public void setFechaFinSeguidor(Date fechaFinSeguidor) {
        this.fechaFinSeguidor = fechaFinSeguidor;
    }
    
}
