package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TicketRegistro generated by hbm2java
 */
@Entity
@Table(name = "ticket_registro")
public class TicketRegistro implements java.io.Serializable {

	private int idTicketRegistro;
	private EstatusTicketRegistro estatusTicketRegistro;
	private Usuario usuario;
	private TipoTicketRegistro tipoTicketRegistro;
	private Date fechaTicketRegistro;
	private Date fechaTicketUsado;
	private String textoTicketRegistro;
	private Set<Invitacion> invitacions = new HashSet<Invitacion>(0);
	private Set<Envio> envios = new HashSet<Envio>(0);
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public TicketRegistro() {
	}

	public TicketRegistro(int idTicketRegistro,
			EstatusTicketRegistro estatusTicketRegistro, Usuario usuario,
			TipoTicketRegistro tipoTicketRegistro, Date fechaTicketRegistro,
			String textoTicketRegistro) {
		this.idTicketRegistro = idTicketRegistro;
		this.estatusTicketRegistro = estatusTicketRegistro;
		this.usuario = usuario;
		this.tipoTicketRegistro = tipoTicketRegistro;
		this.fechaTicketRegistro = fechaTicketRegistro;
		this.textoTicketRegistro = textoTicketRegistro;
	}
	public TicketRegistro(int idTicketRegistro,
			EstatusTicketRegistro estatusTicketRegistro, Usuario usuario,
			TipoTicketRegistro tipoTicketRegistro, Date fechaTicketRegistro,
			Date fechaTicketUsado, String textoTicketRegistro,
			Set<Invitacion> invitacions, Set<Envio> envios, Set<Aviso> avisos) {
		this.idTicketRegistro = idTicketRegistro;
		this.estatusTicketRegistro = estatusTicketRegistro;
		this.usuario = usuario;
		this.tipoTicketRegistro = tipoTicketRegistro;
		this.fechaTicketRegistro = fechaTicketRegistro;
		this.fechaTicketUsado = fechaTicketUsado;
		this.textoTicketRegistro = textoTicketRegistro;
		this.invitacions = invitacions;
		this.envios = envios;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "id_ticket_registro", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdTicketRegistro() {
		return this.idTicketRegistro;
	}

	public void setIdTicketRegistro(int idTicketRegistro) {
		this.idTicketRegistro = idTicketRegistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_ticket_registro_id", nullable = false)
	@NotNull
	public EstatusTicketRegistro getEstatusTicketRegistro() {
		return this.estatusTicketRegistro;
	}

	public void setEstatusTicketRegistro(
			EstatusTicketRegistro estatusTicketRegistro) {
		this.estatusTicketRegistro = estatusTicketRegistro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_ticket_registro_id", nullable = false)
	@NotNull
	public TipoTicketRegistro getTipoTicketRegistro() {
		return this.tipoTicketRegistro;
	}

	public void setTipoTicketRegistro(TipoTicketRegistro tipoTicketRegistro) {
		this.tipoTicketRegistro = tipoTicketRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ticket_registro", nullable = false, length = 13)
	@NotNull
	public Date getFechaTicketRegistro() {
		return this.fechaTicketRegistro;
	}

	public void setFechaTicketRegistro(Date fechaTicketRegistro) {
		this.fechaTicketRegistro = fechaTicketRegistro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_ticket_usado", length = 13)
	public Date getFechaTicketUsado() {
		return this.fechaTicketUsado;
	}

	public void setFechaTicketUsado(Date fechaTicketUsado) {
		this.fechaTicketUsado = fechaTicketUsado;
	}

	@Column(name = "texto_ticket_registro", nullable = false, length = 128)
	@NotNull
	@Length(max = 128)
	public String getTextoTicketRegistro() {
		return this.textoTicketRegistro;
	}

	public void setTextoTicketRegistro(String textoTicketRegistro) {
		this.textoTicketRegistro = textoTicketRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketRegistro")
	public Set<Invitacion> getInvitacions() {
		return this.invitacions;
	}

	public void setInvitacions(Set<Invitacion> invitacions) {
		this.invitacions = invitacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketRegistro")
	public Set<Envio> getEnvios() {
		return this.envios;
	}

	public void setEnvios(Set<Envio> envios) {
		this.envios = envios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketRegistro")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

}
