package mx.uam.azc.link.model;
// Generated 13/07/2011 12:55:13 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoIdea generated by hbm2java
 */
@Entity
@Table(name = "tipo_idea")
public class TipoIdea implements java.io.Serializable {

	private int idTipoIdea;
	private String nombreTipoIdea;
	private String descripcionTipoIdea;
	private Set<ClasificacionIdea> clasificacionIdeas =
                    new HashSet<ClasificacionIdea>(0);
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public TipoIdea() {
	}

	public TipoIdea(int idTipoIdea, String nombreTipoIdea,
			String descripcionTipoIdea) {
		this.idTipoIdea = idTipoIdea;
		this.nombreTipoIdea = nombreTipoIdea;
		this.descripcionTipoIdea = descripcionTipoIdea;
	}

        public TipoIdea(int idTipoIdea, String nombreTipoIdea,
            String descripcionTipoIdea,
            Set<ClasificacionIdea> clasificacionIdeas) {
        this.idTipoIdea = idTipoIdea;
        this.nombreTipoIdea = nombreTipoIdea;
        this.descripcionTipoIdea = descripcionTipoIdea;
        this.clasificacionIdeas = clasificacionIdeas;
    }

	public TipoIdea(int idTipoIdea, String nombreTipoIdea,
			String descripcionTipoIdea,
			Set<ClasificacionIdea> clasificacionIdeas, Set<Visita> visitas) {
		this.idTipoIdea = idTipoIdea;
		this.nombreTipoIdea = nombreTipoIdea;
		this.descripcionTipoIdea = descripcionTipoIdea;
		this.clasificacionIdeas = clasificacionIdeas;
		this.visitas = visitas;
	}

	@Id
	@Column(name = "id_tipo_idea", unique = true, nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
	public int getIdTipoIdea() {
		return this.idTipoIdea;
	}

	public void setIdTipoIdea(int idTipoIdea) {
		this.idTipoIdea = idTipoIdea;
	}

	@Column(name = "nombre_tipo_idea", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoIdea() {
		return this.nombreTipoIdea;
	}

	public void setNombreTipoIdea(String nombreTipoIdea) {
		this.nombreTipoIdea = nombreTipoIdea;
	}

	@Column(name = "descripcion_tipo_idea", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionTipoIdea() {
		return this.descripcionTipoIdea;
	}

	public void setDescripcionTipoIdea(String descripcionTipoIdea) {
		this.descripcionTipoIdea = descripcionTipoIdea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIdea")
	public Set<ClasificacionIdea> getClasificacionIdeas() {
		return this.clasificacionIdeas;
	}

    public void setClasificacionIdeas
                                   (Set<ClasificacionIdea> clasificacionIdeas) {
		this.clasificacionIdeas = clasificacionIdeas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoIdea")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

}
