package mx.uam.azc.link.model;
// Generated 11/07/2011 09:31:10 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoVista generated by hbm2java
 */
@Entity
@Table(name = "tipo_vista")
public class TipoVista implements java.io.Serializable {

	private int idTipoVista;
	private String nombreTipoVista;
	private String descripcionTipoVista;
	private Set<Vista> vistas = new HashSet<Vista>(0);

	public TipoVista() {
	}

	public TipoVista(int idTipoVista, String nombreTipoVista,
			String descripcionTipoVista) {
		this.idTipoVista = idTipoVista;
		this.nombreTipoVista = nombreTipoVista;
		this.descripcionTipoVista = descripcionTipoVista;
	}
	public TipoVista(int idTipoVista, String nombreTipoVista,
			String descripcionTipoVista, Set<Vista> vistas) {
		this.idTipoVista = idTipoVista;
		this.nombreTipoVista = nombreTipoVista;
		this.descripcionTipoVista = descripcionTipoVista;
		this.vistas = vistas;
	}

	@Id
	@Column(name = "id_tipo_vista", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdTipoVista() {
		return this.idTipoVista;
	}

	public void setIdTipoVista(int idTipoVista) {
		this.idTipoVista = idTipoVista;
	}

	@Column(name = "nombre_tipo_vista", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoVista() {
		return this.nombreTipoVista;
	}

	public void setNombreTipoVista(String nombreTipoVista) {
		this.nombreTipoVista = nombreTipoVista;
	}

	@Column(name = "descripcion_tipo_vista", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionTipoVista() {
		return this.descripcionTipoVista;
	}

	public void setDescripcionTipoVista(String descripcionTipoVista) {
		this.descripcionTipoVista = descripcionTipoVista;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVista")
	public Set<Vista> getVistas() {
		return this.vistas;
	}

	public void setVistas(Set<Vista> vistas) {
		this.vistas = vistas;
	}

}
