package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoBitacora generated by hbm2java
 */
@Entity
@Table(name = "tipo_bitacora")
public class TipoBitacora implements java.io.Serializable {

    private int idTipoBitacora;
    private String nombreTipoBitacora;
    private String definicionTipoBitacora;
    private Set<Bitacora> bitacoras = new HashSet<Bitacora>(0);

    public TipoBitacora() {
    }

    public TipoBitacora(int idTipoBitacora, String nombreTipoBitacora,
            String definicionTipoBitacora) {
        this.idTipoBitacora = idTipoBitacora;
        this.nombreTipoBitacora = nombreTipoBitacora;
        this.definicionTipoBitacora = definicionTipoBitacora;
    }

    public TipoBitacora(int idTipoBitacora, String nombreTipoBitacora,
            String definicionTipoBitacora, Set<Bitacora> bitacoras) {
        this.idTipoBitacora = idTipoBitacora;
        this.nombreTipoBitacora = nombreTipoBitacora;
        this.definicionTipoBitacora = definicionTipoBitacora;
        this.bitacoras = bitacoras;
    }

    @Id
    @Column(name = "id_tipo_bitacora", unique = true, nullable = false)
    public int getIdTipoBitacora() {
        return this.idTipoBitacora;
    }

    public void setIdTipoBitacora(int idTipoBitacora) {
        this.idTipoBitacora = idTipoBitacora;
    }

    @Column(name = "nombre_tipo_bitacora", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreTipoBitacora() {
        return this.nombreTipoBitacora;
    }

    public void setNombreTipoBitacora(String nombreTipoBitacora) {
        this.nombreTipoBitacora = nombreTipoBitacora;
    }

    @Column(name = "definicion_tipo_bitacora", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionTipoBitacora() {
        return this.definicionTipoBitacora;
    }

    public void setDefinicionTipoBitacora(String definicionTipoBitacora) {
        this.definicionTipoBitacora = definicionTipoBitacora;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoBitacora")
    public Set<Bitacora> getBitacoras() {
        return this.bitacoras;
    }

    public void setBitacoras(Set<Bitacora> bitacoras) {
        this.bitacoras = bitacoras;
    }
}
