package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoTicketRegistro generated by hbm2java
 */
@Entity
@Table(name = "tipo_ticket_registro")
public class TipoTicketRegistro implements java.io.Serializable {

	private int idTipoTicketRegistro;
	private String nombreTipoTicketRegistro;
	private String descripcionTipoTicketRegistro;
	private Set<TicketRegistro> ticketRegistros = new HashSet<TicketRegistro>(0);

	public TipoTicketRegistro() {
	}

	public TipoTicketRegistro(int idTipoTicketRegistro,
			String nombreTipoTicketRegistro,
			String descripcionTipoTicketRegistro) {
		this.idTipoTicketRegistro = idTipoTicketRegistro;
		this.nombreTipoTicketRegistro = nombreTipoTicketRegistro;
		this.descripcionTipoTicketRegistro = descripcionTipoTicketRegistro;
	}
	public TipoTicketRegistro(int idTipoTicketRegistro,
			String nombreTipoTicketRegistro,
			String descripcionTipoTicketRegistro,
			Set<TicketRegistro> ticketRegistros) {
		this.idTipoTicketRegistro = idTipoTicketRegistro;
		this.nombreTipoTicketRegistro = nombreTipoTicketRegistro;
		this.descripcionTipoTicketRegistro = descripcionTipoTicketRegistro;
		this.ticketRegistros = ticketRegistros;
	}

	@Id
	@Column(name = "id_tipo_ticket_registro", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdTipoTicketRegistro() {
		return this.idTipoTicketRegistro;
	}

	public void setIdTipoTicketRegistro(int idTipoTicketRegistro) {
		this.idTipoTicketRegistro = idTipoTicketRegistro;
	}

	@Column(name = "nombre_tipo_ticket_registro", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoTicketRegistro() {
		return this.nombreTipoTicketRegistro;
	}

	public void setNombreTipoTicketRegistro(String nombreTipoTicketRegistro) {
		this.nombreTipoTicketRegistro = nombreTipoTicketRegistro;
	}

	@Column(name = "descripcion_tipo_ticket_registro", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionTipoTicketRegistro() {
		return this.descripcionTipoTicketRegistro;
	}

	public void setDescripcionTipoTicketRegistro(
			String descripcionTipoTicketRegistro) {
		this.descripcionTipoTicketRegistro = descripcionTipoTicketRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTicketRegistro")
	public Set<TicketRegistro> getTicketRegistros() {
		return this.ticketRegistros;
	}

	public void setTicketRegistros(Set<TicketRegistro> ticketRegistros) {
		this.ticketRegistros = ticketRegistros;
	}

}
