package mx.uam.azc.link.model;
// Generated 11/06/2011 09:16:22 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoContactoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_contacto_usuario")
public class TipoContactoUsuario implements java.io.Serializable {

	private int idTipoContactoUsuario;
	private String nombreTipoContactoUsuario;
	private String definicionTipoContactoUsuario;
	private String dato1;
	private String dato2;
	private String dato3;
	private String dato4;
	private Set<ContactoUsuario> contactoUsuarios = new HashSet<ContactoUsuario>(
			0);

	public TipoContactoUsuario() {
	}

	public TipoContactoUsuario(int idTipoContactoUsuario,
			String nombreTipoContactoUsuario,
			String definicionTipoContactoUsuario) {
		this.idTipoContactoUsuario = idTipoContactoUsuario;
		this.nombreTipoContactoUsuario = nombreTipoContactoUsuario;
		this.definicionTipoContactoUsuario = definicionTipoContactoUsuario;
	}

        public TipoContactoUsuario(int idTipoContactoUsuario,
            String nombreTipoContactoUsuario,
            String definicionTipoContactoUsuario,
            Set<ContactoUsuario> contactoUsuarios) {
        this.idTipoContactoUsuario = idTipoContactoUsuario;
        this.nombreTipoContactoUsuario = nombreTipoContactoUsuario;
        this.definicionTipoContactoUsuario = definicionTipoContactoUsuario;
        this.contactoUsuarios = contactoUsuarios;
    }

	public TipoContactoUsuario(int idTipoContactoUsuario,
			String nombreTipoContactoUsuario,
			String definicionTipoContactoUsuario, String dato1, String dato2,
			String dato3, String dato4, Set<ContactoUsuario> contactoUsuarios) {
		this.idTipoContactoUsuario = idTipoContactoUsuario;
		this.nombreTipoContactoUsuario = nombreTipoContactoUsuario;
		this.definicionTipoContactoUsuario = definicionTipoContactoUsuario;
		this.dato1 = dato1;
		this.dato2 = dato2;
		this.dato3 = dato3;
		this.dato4 = dato4;
		this.contactoUsuarios = contactoUsuarios;
	}

	@Id
	@Column(name = "id_tipo_contacto_usuario", unique = true, nullable = false)
	public int getIdTipoContactoUsuario() {
		return this.idTipoContactoUsuario;
	}

	public void setIdTipoContactoUsuario(int idTipoContactoUsuario) {
		this.idTipoContactoUsuario = idTipoContactoUsuario;
	}

	@Column(name = "nombre_tipo_contacto_usuario", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoContactoUsuario() {
		return this.nombreTipoContactoUsuario;
	}

	public void setNombreTipoContactoUsuario(String nombreTipoContactoUsuario) {
		this.nombreTipoContactoUsuario = nombreTipoContactoUsuario;
	}

	@Column(name = "definicion_tipo_contacto_usuario", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDefinicionTipoContactoUsuario() {
		return this.definicionTipoContactoUsuario;
	}

	public void setDefinicionTipoContactoUsuario(
			String definicionTipoContactoUsuario) {
		this.definicionTipoContactoUsuario = definicionTipoContactoUsuario;
	}

	@Column(name = "dato1", length = 100)
	@Length(max = 100)
	public String getDato1() {
		return this.dato1;
	}

	public void setDato1(String dato1) {
		this.dato1 = dato1;
	}

	@Column(name = "dato2", length = 100)
	@Length(max = 100)
	public String getDato2() {
		return this.dato2;
	}

	public void setDato2(String dato2) {
		this.dato2 = dato2;
	}

	@Column(name = "dato3", length = 100)
	@Length(max = 100)
	public String getDato3() {
		return this.dato3;
	}

	public void setDato3(String dato3) {
		this.dato3 = dato3;
	}

	@Column(name = "dato4", length = 100)
	@Length(max = 100)
	public String getDato4() {
		return this.dato4;
	}

	public void setDato4(String dato4) {
		this.dato4 = dato4;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContactoUsuario")
	public Set<ContactoUsuario> getContactoUsuarios() {
		return this.contactoUsuarios;
	}

	public void setContactoUsuarios(Set<ContactoUsuario> contactoUsuarios) {
		this.contactoUsuarios = contactoUsuarios;
	}

}
