package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoAviso generated by hbm2java
 */
@Entity
@Table(name = "tipo_aviso")
public class TipoAviso implements java.io.Serializable {

	private int idTipoAviso;
	private String nombreTipoAviso;
	private String definicionTipoAviso;
	private Set<Aviso> avisos = new HashSet<Aviso>(0);

	public TipoAviso() {
	}

	public TipoAviso(int idTipoAviso, String nombreTipoAviso,
			String definicionTipoAviso) {
		this.idTipoAviso = idTipoAviso;
		this.nombreTipoAviso = nombreTipoAviso;
		this.definicionTipoAviso = definicionTipoAviso;
	}
	public TipoAviso(int idTipoAviso, String nombreTipoAviso,
			String definicionTipoAviso, Set<Aviso> avisos) {
		this.idTipoAviso = idTipoAviso;
		this.nombreTipoAviso = nombreTipoAviso;
		this.definicionTipoAviso = definicionTipoAviso;
		this.avisos = avisos;
	}

	@Id
	@Column(name = "id_tipo_aviso", unique = true, nullable = false)
	public int getIdTipoAviso() {
		return this.idTipoAviso;
	}

	public void setIdTipoAviso(int idTipoAviso) {
		this.idTipoAviso = idTipoAviso;
	}

	@Column(name = "nombre_tipo_aviso", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoAviso() {
		return this.nombreTipoAviso;
	}

	public void setNombreTipoAviso(String nombreTipoAviso) {
		this.nombreTipoAviso = nombreTipoAviso;
	}

	@Column(name = "definicion_tipo_aviso", nullable = false)
	@NotNull
	public String getDefinicionTipoAviso() {
		return this.definicionTipoAviso;
	}

	public void setDefinicionTipoAviso(String definicionTipoAviso) {
		this.definicionTipoAviso = definicionTipoAviso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAviso")
	public Set<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set<Aviso> avisos) {
		this.avisos = avisos;
	}

}
