package mx.uam.azc.link.model;
// Generated 22/06/2011 08:54:16 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoVisita generated by hbm2java
 */
@Entity
@Table(name = "tipo_visita")
public class TipoVisita implements java.io.Serializable {

	private int idTipoVisita;
	private String nombreTipoVisita;
	private String descripcionTipoVisita;
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public TipoVisita() {
	}

	public TipoVisita(int idTipoVisita, String nombreTipoVisita,
			String descripcionTipoVisita) {
		this.idTipoVisita = idTipoVisita;
		this.nombreTipoVisita = nombreTipoVisita;
		this.descripcionTipoVisita = descripcionTipoVisita;
	}
	public TipoVisita(int idTipoVisita, String nombreTipoVisita,
			String descripcionTipoVisita, Set<Visita> visitas) {
		this.idTipoVisita = idTipoVisita;
		this.nombreTipoVisita = nombreTipoVisita;
		this.descripcionTipoVisita = descripcionTipoVisita;
		this.visitas = visitas;
	}

	@Id
	@Column(name = "id_tipo_visita", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdTipoVisita() {
		return this.idTipoVisita;
	}

	public void setIdTipoVisita(int idTipoVisita) {
		this.idTipoVisita = idTipoVisita;
	}

	@Column(name = "nombre_tipo_visita", nullable = false, length = 15)
	@NotNull
	@Length(max = 15)
	public String getNombreTipoVisita() {
		return this.nombreTipoVisita;
	}

	public void setNombreTipoVisita(String nombreTipoVisita) {
		this.nombreTipoVisita = nombreTipoVisita;
	}

	@Column(name = "descripcion_tipo_visita", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionTipoVisita() {
		return this.descripcionTipoVisita;
	}

	public void setDescripcionTipoVisita(String descripcionTipoVisita) {
		this.descripcionTipoVisita = descripcionTipoVisita;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVisita")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

}
