package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoCritica generated by hbm2java
 */
@Entity
@Table(name = "tipo_critica")
public class TipoCritica implements java.io.Serializable {

    private int idTipoCritica;
    private String nombreTipoCritica;
    private String definicionTipoCritica;
    private Set<Critica> criticas = new HashSet<Critica>(0);

    public TipoCritica() {
    }

    public TipoCritica(int idTipoCritica, String nombreTipoCritica,
            String definicionTipoCritica) {
        this.idTipoCritica = idTipoCritica;
        this.nombreTipoCritica = nombreTipoCritica;
        this.definicionTipoCritica = definicionTipoCritica;
    }

    public TipoCritica(int idTipoCritica, String nombreTipoCritica,
            String definicionTipoCritica, Set<Critica> criticas) {
        this.idTipoCritica = idTipoCritica;
        this.nombreTipoCritica = nombreTipoCritica;
        this.definicionTipoCritica = definicionTipoCritica;
        this.criticas = criticas;
    }

    @Id
    @Column(name = "id_tipo_critica", unique = true, nullable = false)
    public int getIdTipoCritica() {
        return this.idTipoCritica;
    }

    public void setIdTipoCritica(int idTipoCritica) {
        this.idTipoCritica = idTipoCritica;
    }

    @Column(name = "nombre_tipo_critica", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreTipoCritica() {
        return this.nombreTipoCritica;
    }

    public void setNombreTipoCritica(String nombreTipoCritica) {
        this.nombreTipoCritica = nombreTipoCritica;
    }

    @Column(name = "definicion_tipo_critica", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionTipoCritica() {
        return this.definicionTipoCritica;
    }

    public void setDefinicionTipoCritica(String definicionTipoCritica) {
        this.definicionTipoCritica = definicionTipoCritica;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCritica")
    public Set<Critica> getCriticas() {
        return this.criticas;
    }

    public void setCriticas(Set<Critica> criticas) {
        this.criticas = criticas;
    }
}
