package mx.uam.azc.link.model;
// Generated 7/06/2011 11:19:01 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * TipoEnvio generated by hbm2java
 */
@Entity
@Table(name = "tipo_envio")
public class TipoEnvio implements java.io.Serializable {

    private int idTipoEnvio;
    private String nombreTipoEnvio;
    private String definicionTipoEnvio;
    private String vistaTipoEnvio;
    private Set<Envio> envios = new HashSet<Envio>(0);

    public TipoEnvio() {
    }

    public TipoEnvio(int idTipoEnvio, String nombreTipoEnvio,
            String definicionTipoEnvio) {
        this.idTipoEnvio = idTipoEnvio;
        this.nombreTipoEnvio = nombreTipoEnvio;
        this.definicionTipoEnvio = definicionTipoEnvio;
    }

    public TipoEnvio(int idTipoEnvio, String nombreTipoEnvio,
            String definicionTipoEnvio, String vistaTipoEnvio
            , Set<Envio> envios) {
        this.idTipoEnvio = idTipoEnvio;
        this.nombreTipoEnvio = nombreTipoEnvio;
        this.definicionTipoEnvio = definicionTipoEnvio;
        this.vistaTipoEnvio = vistaTipoEnvio;
        this.envios = envios;
    }

    @Id
    @Column(name = "id_tipo_envio", unique = true, nullable = false)
    public int getIdTipoEnvio() {
        return this.idTipoEnvio;
    }

    public void setIdTipoEnvio(int idTipoEnvio) {
        this.idTipoEnvio = idTipoEnvio;
    }

    @Column(name = "nombre_tipo_envio", nullable = false, length = 15)
    @NotNull
    @Length(max = 15)
    public String getNombreTipoEnvio() {
        return this.nombreTipoEnvio;
    }

    public void setNombreTipoEnvio(String nombreTipoEnvio) {
        this.nombreTipoEnvio = nombreTipoEnvio;
    }

    @Column(name = "definicion_tipo_envio", nullable = false, length = 150)
    @NotNull
    @Length(max = 150)
    public String getDefinicionTipoEnvio() {
        return this.definicionTipoEnvio;
    }

    public void setDefinicionTipoEnvio(String definicionTipoEnvio) {
        this.definicionTipoEnvio = definicionTipoEnvio;
    }

    @Column(name = "vista_tipo_envio", length = 100)
    @Length(max = 100)
    public String getVistaTipoEnvio() {
        return this.vistaTipoEnvio;
    }

    public void setVistaTipoEnvio(String vistaTipoEnvio) {
        this.vistaTipoEnvio = vistaTipoEnvio;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEnvio")
    public Set<Envio> getEnvios() {
        return this.envios;
    }

    public void setEnvios(Set<Envio> envios) {
        this.envios = envios;
    }
}
