package mx.uam.azc.link.model;
// Generated 13/07/2011 12:55:13 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Visita generated by hbm2java
 */
@Entity
@Table(name = "visita")
public class Visita implements java.io.Serializable {

	private long idVisita;
	private Pregunta pregunta;
	private Idea idea;
	private Usuario usuario;
	private EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos;
	private TipoVisita tipoVisita;
	private Vista vista;
	private Institucion institucion;
	private TipoIdea tipoIdea;
	private Date fechaInicioVisita;
	private Date fechaFinVisita;
	private String direccionIpVisita;
	private Float coordenadaGeograficaLongitudVisita;
	private Float coordenadaGeograficaLatitudVisita;
	private String sesionid;
	private Integer limiteInicial;
	private Integer limiteFinal;
	private String textoABuscar;

	public Visita() {
	}

	public Visita(long idVisita, TipoVisita tipoVisita, Vista vista,
			Date fechaInicioVisita, String direccionIpVisita, String sesionid) {
		this.idVisita = idVisita;
		this.tipoVisita = tipoVisita;
		this.vista = vista;
		this.fechaInicioVisita = fechaInicioVisita;
		this.direccionIpVisita = direccionIpVisita;
		this.sesionid = sesionid;
	}
        public Visita(long idVisita, Idea idea, Usuario usuario,
			TipoVisita tipoVisita, Vista vista, Date fechaInicioVisita,
			Date fechaFinVisita, String direccionIpVisita,
			Float coordenadaGeograficaLongitudVisita,
			Float coordenadaGeograficaLatitudVisita, String sesionid) {
		this.idVisita = idVisita;
		this.idea = idea;
		this.usuario = usuario;
		this.tipoVisita = tipoVisita;
		this.vista = vista;
		this.fechaInicioVisita = fechaInicioVisita;
		this.fechaFinVisita = fechaFinVisita;
		this.direccionIpVisita = direccionIpVisita;
		this.coordenadaGeograficaLongitudVisita = coordenadaGeograficaLongitudVisita;
		this.coordenadaGeograficaLatitudVisita = coordenadaGeograficaLatitudVisita;
		this.sesionid = sesionid;
	}
	public Visita(long idVisita, Pregunta pregunta, Idea idea, Usuario usuario,
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos,
			TipoVisita tipoVisita, Vista vista, Institucion institucion,
			TipoIdea tipoIdea, Date fechaInicioVisita, Date fechaFinVisita,
			String direccionIpVisita, Float coordenadaGeograficaLongitudVisita,
			Float coordenadaGeograficaLatitudVisita, String sesionid,
			Integer limiteInicial, Integer limiteFinal, String textoABuscar) {
		this.idVisita = idVisita;
		this.pregunta = pregunta;
		this.idea = idea;
		this.usuario = usuario;
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
		this.tipoVisita = tipoVisita;
		this.vista = vista;
		this.institucion = institucion;
		this.tipoIdea = tipoIdea;
		this.fechaInicioVisita = fechaInicioVisita;
		this.fechaFinVisita = fechaFinVisita;
		this.direccionIpVisita = direccionIpVisita;
		this.coordenadaGeograficaLongitudVisita = coordenadaGeograficaLongitudVisita;
		this.coordenadaGeograficaLatitudVisita = coordenadaGeograficaLatitudVisita;
		this.sesionid = sesionid;
		this.limiteInicial = limiteInicial;
		this.limiteFinal = limiteFinal;
		this.textoABuscar = textoABuscar;
	}

	@Id
	@Column(name = "id_visita", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public long getIdVisita() {
		return this.idVisita;
	}

	public void setIdVisita(long idVisita) {
		this.idVisita = idVisita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pregunta_id")
	public Pregunta getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(Pregunta pregunta) {
		this.pregunta = pregunta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idea_id")
	public Idea getIdea() {
		return this.idea;
	}

	public void setIdea(Idea idea) {
		this.idea = idea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuario_id")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estatus_ayuda_recursos_humanos_id")
	public EstatusAyudaRecursosHumanos getEstatusAyudaRecursosHumanos() {
		return this.estatusAyudaRecursosHumanos;
	}

	public void setEstatusAyudaRecursosHumanos(
			EstatusAyudaRecursosHumanos estatusAyudaRecursosHumanos) {
		this.estatusAyudaRecursosHumanos = estatusAyudaRecursosHumanos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_visita_id", nullable = false)
	@NotNull
	public TipoVisita getTipoVisita() {
		return this.tipoVisita;
	}

	public void setTipoVisita(TipoVisita tipoVisita) {
		this.tipoVisita = tipoVisita;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vista_id", nullable = false)
	@NotNull
	public Vista getVista() {
		return this.vista;
	}

	public void setVista(Vista vista) {
		this.vista = vista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "institucion_id")
	public Institucion getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(Institucion institucion) {
		this.institucion = institucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_idea_id")
	public TipoIdea getTipoIdea() {
		return this.tipoIdea;
	}

	public void setTipoIdea(TipoIdea tipoIdea) {
		this.tipoIdea = tipoIdea;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_inicio_visita", nullable = false, length = 13)
	@NotNull
	public Date getFechaInicioVisita() {
		return this.fechaInicioVisita;
	}

	public void setFechaInicioVisita(Date fechaInicioVisita) {
		this.fechaInicioVisita = fechaInicioVisita;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_fin_visita", length = 13)
	public Date getFechaFinVisita() {
		return this.fechaFinVisita;
	}

	public void setFechaFinVisita(Date fechaFinVisita) {
		this.fechaFinVisita = fechaFinVisita;
	}

	@Column(name = "direccion_ip_visita", nullable = false, length = 40)
	@NotNull
	@Length(max = 40)
	public String getDireccionIpVisita() {
		return this.direccionIpVisita;
	}

	public void setDireccionIpVisita(String direccionIpVisita) {
		this.direccionIpVisita = direccionIpVisita;
	}

	@Column(name = "coordenada_geografica_longitud_visita", precision = 8, scale = 8)
	public Float getCoordenadaGeograficaLongitudVisita() {
		return this.coordenadaGeograficaLongitudVisita;
	}

	public void setCoordenadaGeograficaLongitudVisita(
			Float coordenadaGeograficaLongitudVisita) {
		this.coordenadaGeograficaLongitudVisita = coordenadaGeograficaLongitudVisita;
	}

	@Column(name = "coordenada_geografica_latitud_visita", precision = 8, scale = 8)
	public Float getCoordenadaGeograficaLatitudVisita() {
		return this.coordenadaGeograficaLatitudVisita;
	}

	public void setCoordenadaGeograficaLatitudVisita(
			Float coordenadaGeograficaLatitudVisita) {
		this.coordenadaGeograficaLatitudVisita = coordenadaGeograficaLatitudVisita;
	}

	@Column(name = "sesionid", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getSesionid() {
		return this.sesionid;
	}

	public void setSesionid(String sesionid) {
		this.sesionid = sesionid;
	}

	@Column(name = "limite_inicial")
	public Integer getLimiteInicial() {
		return this.limiteInicial;
	}

	public void setLimiteInicial(Integer limiteInicial) {
		this.limiteInicial = limiteInicial;
	}

	@Column(name = "limite_final")
	public Integer getLimiteFinal() {
		return this.limiteFinal;
	}

	public void setLimiteFinal(Integer limiteFinal) {
		this.limiteFinal = limiteFinal;
	}

	@Column(name = "texto_a_buscar", length = 100)
	@Length(max = 100)
	public String getTextoABuscar() {
		return this.textoABuscar;
	}

	public void setTextoABuscar(String textoABuscar) {
		this.textoABuscar = textoABuscar;
	}

}
