package mx.uam.azc.link.model;
// Generated 11/07/2011 09:31:10 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Vista generated by hbm2java
 */
@Entity
@Table(name = "vista")
public class Vista implements java.io.Serializable {

	private int idVista;
	private TipoVista tipoVista;
	private String descripcionVista;
	private String nombreVista;
	private Set<Visita> visitas = new HashSet<Visita>(0);

	public Vista() {
	}

	public Vista(int idVista, TipoVista tipoVista, String descripcionVista,
			String nombreVista) {
		this.idVista = idVista;
		this.tipoVista = tipoVista;
		this.descripcionVista = descripcionVista;
		this.nombreVista = nombreVista;
	}
	public Vista(int idVista, TipoVista tipoVista, String descripcionVista,
			String nombreVista, Set<Visita> visitas) {
		this.idVista = idVista;
		this.tipoVista = tipoVista;
		this.descripcionVista = descripcionVista;
		this.nombreVista = nombreVista;
		this.visitas = visitas;
	}

	@Id
	@Column(name = "id_vista", unique = true, nullable = false)
        @GeneratedValue(strategy=GenerationType.SEQUENCE)
	public int getIdVista() {
		return this.idVista;
	}

	public void setIdVista(int idVista) {
		this.idVista = idVista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_vista_id", nullable = false)
	@NotNull
	public TipoVista getTipoVista() {
		return this.tipoVista;
	}

	public void setTipoVista(TipoVista tipoVista) {
		this.tipoVista = tipoVista;
	}

	@Column(name = "descripcion_vista", nullable = false, length = 150)
	@NotNull
	@Length(max = 150)
	public String getDescripcionVista() {
		return this.descripcionVista;
	}

	public void setDescripcionVista(String descripcionVista) {
		this.descripcionVista = descripcionVista;
	}

	@Column(name = "nombre_vista", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getNombreVista() {
		return this.nombreVista;
	}

	public void setNombreVista(String nombreVista) {
		this.nombreVista = nombreVista;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vista")
	public Set<Visita> getVisitas() {
		return this.visitas;
	}

	public void setVisitas(Set<Visita> visitas) {
		this.visitas = visitas;
	}

}
